// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import { IconChevronLeft, IconChevronRight } from '@/assets/icons';
import { IconButton } from '@/components/buttons/IconButton';
import {
  ObservationCard,
  type ObservationCardSize,
} from '@/components/cards/ObservationCard';
import { ThemedText } from '@/components/text/ThemedText';
import { Size } from '@/constants/theme';
import { useLayoutChrome } from '@/context/LayoutChromeContext';
import { useResponsive } from '@/hooks/useResponsive';
import React from 'react';
import { Platform, StyleSheet, View } from 'react-native';
import { anchorScrollMarginStyle } from '@/utils/anchors';

export type ObservationGalleryPoint = {
  catalogNumber: string;
  catalogAutoGenerated?: boolean;
  varValue: number | null;
  varColor: string | null;
  varLabel: string | null;
  varShape?: string | null;
  imageUrl?: string | null;
  license?: string | null;
  licenseUrl?: string | null;
  attribution?: string | null;
  /** This observation's OWN taxon — for a species/infraspecific page every
   * point trivially observes the page's own taxon, but for a large taxon
   * (genus/family/kingdom) a single gallery page can span many different
   * descendant species, so each point carries its own (see
   * SpeciesOccurrence.taxonId/scientificName's doc comment). */
  taxonId?: string | null;
  scientificName?: string | null;
};

type SpeciesObservationGalleryProps = {
  points: ObservationGalleryPoint[];
  loading?: boolean;
  /** Selects/pans to the matching pin on the map when a card is pressed. */
  onCardPress?: (catalogNumber: string) => void;
  /** Card size — the caller picks 'compact' on narrow viewports so more fit per row. */
  cardSize?: ObservationCardSize;
  /** 0-indexed current page — mirrors Filters.tsx's listOffset/pageSize pager. */
  page: number;
  onPageChange: (page: number) => void;
  pageSize: number;
  /** Total matching points across all pages, before pagination slicing. */
  totalCount: number;
};

export function SpeciesObservationGallery({
  points,
  loading = false,
  onCardPress,
  cardSize = 'default',
  page,
  onPageChange,
  pageSize,
  totalCount,
}: SpeciesObservationGalleryProps) {
  const responsive = useResponsive();
  const { webHeaderHeight } = useLayoutChrome();

  // Gate on totalCount, not points.length — points can legitimately be
  // empty for a moment on an out-of-range page (e.g. a mobile rotation
  // shrinking pageSize while sitting on a later page, before the parent's
  // clamp effect catches up). Hiding the whole section — pager included —
  // in that case strands the user with no way back to a valid page.
  if (!loading && totalCount === 0) {
    return null;
  }

  const totalPages = Math.max(1, Math.ceil(totalCount / Math.max(1, pageSize)));
  const currentPage = page + 1;
  const canGoPrevious = page > 0;
  const canGoNext = currentPage < totalPages;
  const onPreviousPage = () => onPageChange(Math.max(0, page - 1));
  const onNextPage = () => onPageChange(page + 1);

  return (
    <View style={styles.container}>
      <ThemedText
        variant='subheading'
        {...(Platform.OS === 'web'
          ? {
              nativeID: 'observations',
              style: anchorScrollMarginStyle(
                webHeaderHeight,
                responsive.breakpoint,
              ),
            }
          : {})}
      >
        Observations
      </ThemedText>
      {loading && points.length === 0 ? (
        <ThemedText variant='bodySmall'>Loading…</ThemedText>
      ) : (
        <View style={styles.grid}>
          {points.map((point) => (
            <ObservationCard
              key={point.catalogNumber}
              catalogNumber={point.catalogNumber}
              catalogAutoGenerated={point.catalogAutoGenerated}
              scientificName={point.scientificName}
              taxonId={point.taxonId}
              varLabel={point.varLabel}
              varColor={point.varColor}
              varShape={point.varShape}
              imageUrl={point.imageUrl}
              license={point.license}
              licenseUrl={point.licenseUrl}
              attribution={point.attribution}
              size={cardSize}
              onPress={
                onCardPress ? () => onCardPress(point.catalogNumber) : undefined
              }
            />
          ))}
        </View>
      )}
      {totalPages > 1 && (
        <View style={styles.pagerRow}>
          <IconButton
            icon={<IconChevronLeft />}
            variant='neutral'
            size='medium'
            disabled={!canGoPrevious}
            accessibilityLabel='Previous page'
            onPress={onPreviousPage}
          />
          <ThemedText variant='body'>
            Page {currentPage} of {totalPages}
          </ThemedText>
          <IconButton
            icon={<IconChevronRight />}
            variant='neutral'
            size='medium'
            disabled={!canGoNext}
            accessibilityLabel='Next page'
            onPress={onNextPage}
          />
        </View>
      )}
    </View>
  );
}

export default SpeciesObservationGallery;

const styles = StyleSheet.create({
  container: {
    gap: Size.space['300'],
    marginTop: Size.space['600'],
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Size.space['300'],
  },
  pagerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Size.space['200'],
    marginBottom: Size.space['600'],
  },
});
