// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import { Typography } from '@/constants/theme';
import { fireEvent, render, screen } from '@testing-library/react-native';
import React from 'react';
import { useColorScheme } from '@/hooks/useColorScheme';
import { useTypographyStyles } from '@/hooks/useTypographyStyles';
import {
  SpeciesObservationGallery,
  type ObservationGalleryPoint,
} from '../SpeciesObservationGallery';

jest.mock('@/hooks/useColorScheme', () => ({
  useColorScheme: jest.fn(() => 'dark'),
}));

jest.mock('@/hooks/useTypographyStyles', () => ({
  useTypographyStyles: jest.fn(),
}));

jest.mock('@/components/text/ThemedText', () => {
  const ReactActual = jest.requireActual<typeof import('react')>('react');
  const { Text } =
    jest.requireActual<typeof import('react-native')>('react-native');

  return {
    ThemedText: ({ children, ...props }: { children?: React.ReactNode }) =>
      ReactActual.createElement(Text, props, children),
  };
});

const mockUseColorScheme = useColorScheme as jest.MockedFunction<
  typeof useColorScheme
>;
const mockUseTypographyStyles = useTypographyStyles as jest.MockedFunction<
  typeof useTypographyStyles
>;

const point = (
  overrides: Partial<ObservationGalleryPoint> = {},
): ObservationGalleryPoint => ({
  catalogNumber: '123456',
  varValue: 12.3,
  varColor: '#ff0000',
  varLabel: '12.3°C',
  ...overrides,
});

const defaultPagerProps = {
  page: 0,
  onPageChange: jest.fn(),
  pageSize: 20,
  totalCount: 0,
};

describe('SpeciesObservationGallery', () => {
  beforeEach(() => {
    mockUseColorScheme.mockReturnValue('dark');
    mockUseTypographyStyles.mockReturnValue(Typography.dark);
    defaultPagerProps.onPageChange.mockClear();
  });

  it('renders nothing when there are no points and it is not loading', () => {
    const { toJSON } = render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        points={[]}
        loading={false}
      />,
    );
    expect(toJSON()).toBeNull();
  });

  it('shows a loading state when loading with no points yet', () => {
    render(
      <SpeciesObservationGallery {...defaultPagerProps} points={[]} loading />,
    );
    expect(screen.getByText('Loading…')).toBeTruthy();
  });

  it('renders a card per point, passing through the catalog number and variable fields', () => {
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        totalCount={2}
        points={[
          point({ catalogNumber: '111', varLabel: '5°C', varColor: '#111' }),
          point({ catalogNumber: '222', varLabel: '9°C', varColor: '#222' }),
        ]}
      />,
    );

    expect(screen.getByText('#111')).toBeTruthy();
    expect(screen.getByText('#222')).toBeTruthy();
    expect(screen.getByText('5°C')).toBeTruthy();
    expect(screen.getByText('9°C')).toBeTruthy();
  });

  it('shows the "No data" fallback for a point with no resolved variable value', () => {
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        totalCount={1}
        points={[point({ varValue: null, varColor: null, varLabel: null })]}
      />,
    );
    expect(screen.getByText('No data')).toBeTruthy();
  });

  it('shows a "No media" fallback on every card, matching the map popups until real media data exists', () => {
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        totalCount={2}
        points={[
          point({ catalogNumber: '111' }),
          point({ catalogNumber: '222' }),
        ]}
      />,
    );

    expect(screen.getAllByText('No media')).toHaveLength(2);
  });

  it('passes catalogAutoGenerated through so synthetic catalog numbers are not linked', () => {
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        totalCount={1}
        points={[point({ catalogNumber: '999', catalogAutoGenerated: true })]}
      />,
    );

    const catalogText = screen.getByText('#999');
    expect(catalogText.props.onPress).toBeUndefined();
  });

  it('renders points still while loading, if some are already available', () => {
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        totalCount={1}
        points={[point({ catalogNumber: '111' })]}
        loading
      />,
    );
    expect(screen.getByText('#111')).toBeTruthy();
    expect(screen.queryByText('Loading…')).toBeNull();
  });

  it('hides the pager when everything fits on one page', () => {
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        pageSize={20}
        totalCount={5}
        points={[point()]}
      />,
    );
    expect(screen.queryByText(/Page \d+ of \d+/)).toBeNull();
  });

  it('shows a "Page X of Y" pager when there is more than one page', () => {
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        page={2}
        pageSize={20}
        totalCount={107}
        points={[point()]}
      />,
    );
    expect(screen.getByText('Page 3 of 6')).toBeTruthy();
  });

  it('disables the previous button on the first page and the next button on the last page', () => {
    const { rerender } = render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        page={0}
        pageSize={20}
        totalCount={40}
        points={[point()]}
      />,
    );
    expect(
      screen.getByLabelText('Previous page').props.accessibilityState?.disabled,
    ).toBe(true);
    expect(
      screen.getByLabelText('Next page').props.accessibilityState?.disabled,
    ).toBe(false);

    rerender(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        page={1}
        pageSize={20}
        totalCount={40}
        points={[point()]}
      />,
    );
    expect(
      screen.getByLabelText('Previous page').props.accessibilityState?.disabled,
    ).toBe(false);
    expect(
      screen.getByLabelText('Next page').props.accessibilityState?.disabled,
    ).toBe(true);
  });

  it('calls onCardPress with the catalog number when a card is pressed', () => {
    const onCardPress = jest.fn();
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        totalCount={1}
        onCardPress={onCardPress}
        points={[point({ catalogNumber: '555' })]}
      />,
    );

    fireEvent.press(screen.getByLabelText('Observation #555'));
    expect(onCardPress).toHaveBeenCalledWith('555');
  });

  it('does not make cards pressable when onCardPress is not provided', () => {
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        totalCount={1}
        points={[point({ catalogNumber: '555' })]}
      />,
    );

    expect(screen.queryByLabelText('Observation #555')).toBeNull();
  });

  it('calls onPageChange with the next/previous page index', () => {
    const onPageChange = jest.fn();
    render(
      <SpeciesObservationGallery
        {...defaultPagerProps}
        page={2}
        pageSize={20}
        totalCount={107}
        onPageChange={onPageChange}
        points={[point()]}
      />,
    );

    fireEvent.press(screen.getByLabelText('Next page'));
    expect(onPageChange).toHaveBeenCalledWith(3);

    fireEvent.press(screen.getByLabelText('Previous page'));
    expect(onPageChange).toHaveBeenCalledWith(1);
  });
});
