// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-variable-guides-index.mjs — do not edit
// by hand. Add or remove a .md file in this directory and re-run
// `npm run sync:variable-guides` (or `npm run typecheck`/`npm run web`,
// which already do) to regenerate this file.

import v_circular from './circular.md';
import v_interval from './interval.md';
import v_nominal from './nominal.md';
import v_ordinal from './ordinal.md';
import v_ratio from './ratio.md';

export const TYPE_GUIDES: Record<string, string> = {
  'circular': v_circular,
  'interval': v_interval,
  'nominal': v_nominal,
  'ordinal': v_ordinal,
  'ratio': v_ratio,
};
