// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import { IconImage } from '@/assets/icons';
import { Colors, Size } from '@/constants/theme';
import { useColorScheme } from '@/hooks/useColorScheme';
import React from 'react';
import {
  Image,
  Linking,
  Pressable,
  StyleProp,
  StyleSheet,
  View,
  ViewStyle,
} from 'react-native';
import { ThemedText } from '../text/ThemedText';

export type ObservationCardSize = 'default' | 'compact';

const INAT_OBSERVATION_BASE_URL = 'https://www.inaturalist.org/observations/';

export type ObservationCardProps = {
  catalogNumber: string;
  /** True when catalogNumber was synthesized rather than sourced from iNaturalist — suppresses the observation hyperlink, mirroring point.catalogAutoGenerated in the map popup. */
  catalogAutoGenerated?: boolean;
  /** Caller-formatted variable value text, e.g. "12.3°C" or a class label — mirrors the map popup's varLabel. */
  varLabel?: string | null;
  /** Legend/dot color for the value, matching the map marker color for the same observation. */
  varColor?: string | null;
  imageUrl?: string | null;
  license?: string | null;
  /** Link to the license's terms, e.g. the Creative Commons deed page. Renders the license text as a hyperlink when provided. */
  licenseUrl?: string | null;
  attribution?: string | null;
  size?: ObservationCardSize;
  style?: StyleProp<ViewStyle>;
  onPress?: () => void;
  testID?: string;
};

// Exported so layout math elsewhere (e.g. the below-map gallery computing
// how many cards fit per row) can size against the same width this card
// actually renders at, instead of duplicating the number.
export const DEFAULT_IMAGE_SIZE = 160;
export const COMPACT_IMAGE_SIZE = 96;

export function ObservationCard({
  catalogNumber,
  catalogAutoGenerated = false,
  varLabel,
  varColor,
  imageUrl,
  license,
  licenseUrl,
  attribution,
  size = 'default',
  style,
  onPress,
  testID,
}: ObservationCardProps) {
  const scheme = useColorScheme();
  const mode = scheme === 'dark' ? 'dark' : 'light';
  const palette = Colors[mode];

  const placeholderBackground = palette.background.disabled.default;
  const placeholderIcon = palette.icon.neutral.tertiary;
  const imageSize =
    size === 'compact' ? COMPACT_IMAGE_SIZE : DEFAULT_IMAGE_SIZE;
  const linkStyle = {
    color: palette.text.brand.default,
    textDecorationLine: 'underline' as const,
    textDecorationColor: palette.text.brand.default,
  };
  const isCatalogLinkable = Boolean(catalogNumber) && !catalogAutoGenerated;
  const inatUrl = isCatalogLinkable
    ? `${INAT_OBSERVATION_BASE_URL}${encodeURIComponent(catalogNumber)}`
    : null;

  const content = (
    <View
      collapsable={false}
      style={[styles.container, { width: imageSize }, style]}
    >
      <View
        testID='observation-card-image-wrapper'
        style={[
          styles.imageWrapper,
          { width: imageSize, height: imageSize },
          !imageUrl && { backgroundColor: placeholderBackground },
        ]}
      >
        {imageUrl ? (
          <Image
            testID='observation-card-image'
            source={{ uri: imageUrl }}
            style={styles.image}
            resizeMode='cover'
            accessibilityLabel={`Observation #${catalogNumber}`}
          />
        ) : (
          <View
            style={[
              styles.placeholder,
              { backgroundColor: placeholderBackground },
            ]}
            testID='observation-card-placeholder'
          >
            <IconImage size='20' color={placeholderIcon} />
          </View>
        )}
      </View>

      <View style={styles.textSection}>
        {inatUrl ? (
          <ThemedText
            variant='bodySmallEmphasis'
            numberOfLines={1}
            style={linkStyle}
            accessibilityRole='link'
            onPress={() => Linking.openURL(inatUrl)}
          >
            {`#${catalogNumber}`}
          </ThemedText>
        ) : (
          <ThemedText variant='bodySmallEmphasis' numberOfLines={1}>
            {`#${catalogNumber}`}
          </ThemedText>
        )}
        {varLabel ? (
          <View style={styles.valueRow}>
            {varColor ? (
              <View style={[styles.dot, { backgroundColor: varColor }]} />
            ) : null}
            <ThemedText variant='bodySmall' numberOfLines={1}>
              {varLabel}
            </ThemedText>
          </View>
        ) : (
          <ThemedText
            variant='bodyTiny'
            style={{ color: palette.text.disabled.default }}
          >
            No data
          </ThemedText>
        )}
        {attribution || license ? (
          <View style={styles.creditRow} testID='observation-card-credit'>
            {attribution ? (
              <ThemedText
                variant='bodySmall'
                style={{ color: palette.text.default.tertiary }}
              >
                {attribution}
              </ThemedText>
            ) : null}
            {attribution && license ? (
              <ThemedText
                variant='bodySmall'
                style={{ color: palette.text.default.tertiary }}
              >
                {' · '}
              </ThemedText>
            ) : null}
            {license ? (
              licenseUrl ? (
                <ThemedText
                  variant='bodySmallLink'
                  onPress={() => Linking.openURL(licenseUrl)}
                >
                  {license}
                </ThemedText>
              ) : (
                <ThemedText
                  variant='bodySmall'
                  style={{ color: palette.text.default.tertiary }}
                >
                  {license}
                </ThemedText>
              )
            ) : null}
          </View>
        ) : (
          <ThemedText
            variant='bodyTiny'
            style={{ color: palette.text.disabled.default }}
          >
            No media
          </ThemedText>
        )}
      </View>
    </View>
  );

  if (onPress) {
    return (
      <Pressable
        onPress={onPress}
        accessibilityRole='button'
        accessibilityLabel={`Observation #${catalogNumber}`}
        testID={testID}
      >
        {content}
      </Pressable>
    );
  }

  return (
    <View testID={testID} collapsable={false}>
      {content}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    gap: Size.space['150'],
  },
  imageWrapper: {
    borderRadius: Size.radius['200'],
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  placeholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textSection: {
    gap: Size.space['100'],
  },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Size.space['100'],
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  creditRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'baseline',
  },
});
