// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import { IconImage } from '@/assets/icons';
import { Colors, Size } from '@/constants/theme';
import { useColorScheme } from '@/hooks/useColorScheme';
import { ShapeMarker } from '@/components/sections/speciesOccurrenceMap/ShapeMarker';
import type { ShapeKey } from '@/components/sections/speciesOccurrenceMap/cbColors';
import { toKebabCase } from '@/utils/string';
import type { Href } from 'expo-router';
import React from 'react';
import {
  Image,
  Linking,
  Pressable,
  StyleProp,
  StyleSheet,
  View,
  ViewStyle,
} from 'react-native';
import { RoutePressable } from '../navigation/RoutePressable';
import { ThemedText } from '../text/ThemedText';

export type ObservationCardSize = 'default' | 'compact';

const INAT_OBSERVATION_BASE_URL = 'https://www.inaturalist.org/observations/';

// varShape arrives as a plain string (it's threaded through generic
// Map<string, string> / string | null typing the same way varColor/varLabel
// are), but every value it can actually hold comes from either
// CB_CLASS_SHAPES or aspectToCardinalShape, both already constrained to
// ShapeKey at the source — this just narrows it back for ShapeMarker's sake,
// falling back to a plain dot if an unrecognized value ever shows up rather
// than crashing.
const SHAPE_KEYS: readonly ShapeKey[] = [
  'circle',
  'square',
  'triangle',
  'diamond',
  'ring',
  'triangle-down',
  'cross',
  'plus',
  'star',
  'hexagon',
  'pentagon',
  'arrow',
];
const isShapeKey = (value: string): value is ShapeKey =>
  (SHAPE_KEYS as readonly string[]).includes(value);

export type ObservationCardProps = {
  catalogNumber: string;
  /** True when catalogNumber was synthesized rather than sourced from iNaturalist — suppresses the observation hyperlink, mirroring point.catalogAutoGenerated in the map popup. */
  catalogAutoGenerated?: boolean;
  /** The observed taxon's scientific name — shown above the catalog number, truncated to one line, and (together with taxonId) links to that taxon's species page. */
  scientificName?: string | null;
  /** The observed taxon's id — see scientificName above. Both must resolve to a valid route segment (mirrors SpeciesCard's own href logic) for the name to render as a link; otherwise it renders as plain text. */
  taxonId?: string | null;
  /** Caller-formatted variable value text, e.g. "12.3°C" or a class label — mirrors the map popup's varLabel. */
  varLabel?: string | null;
  /** Legend/dot color for the value, matching the map marker color for the same observation. */
  varColor?: string | null;
  /** Shapes-mode marker shape, matching the map marker for the same observation — mirrors point.varShape. Renders a plain dot when omitted/unrecognized. */
  varShape?: string | null;
  imageUrl?: string | null;
  license?: string | null;
  /** Link to the license's terms, e.g. the Creative Commons deed page. Renders the license text as a hyperlink when provided. */
  licenseUrl?: string | null;
  attribution?: string | null;
  size?: ObservationCardSize;
  style?: StyleProp<ViewStyle>;
  onPress?: () => void;
  testID?: string;
};

// Exported so layout math elsewhere (e.g. the below-map gallery computing
// how many cards fit per row) can size against the same width this card
// actually renders at, instead of duplicating the number.
export const DEFAULT_IMAGE_SIZE = 160;
export const COMPACT_IMAGE_SIZE = 96;

export function ObservationCard({
  catalogNumber,
  catalogAutoGenerated = false,
  scientificName,
  taxonId,
  varLabel,
  varColor,
  varShape,
  imageUrl,
  license,
  licenseUrl,
  attribution,
  size = 'default',
  style,
  onPress,
  testID,
}: ObservationCardProps) {
  const scheme = useColorScheme();
  const mode = scheme === 'dark' ? 'dark' : 'light';
  const palette = Colors[mode];

  const placeholderBackground = palette.background.disabled.default;
  const placeholderIcon = palette.icon.neutral.tertiary;
  const imageSize =
    size === 'compact' ? COMPACT_IMAGE_SIZE : DEFAULT_IMAGE_SIZE;
  const linkStyle = {
    color: palette.text.brand.default,
    textDecorationLine: 'underline' as const,
    textDecorationColor: palette.text.brand.default,
  };
  const isCatalogLinkable = Boolean(catalogNumber) && !catalogAutoGenerated;
  const inatUrl = isCatalogLinkable
    ? `${INAT_OBSERVATION_BASE_URL}${encodeURIComponent(catalogNumber)}`
    : null;

  // Same taxonId+scientificName -> route-segment convention as SpeciesCard's
  // own href logic — kept independent rather than shared since this card
  // only ever needs the resulting href, not SpeciesCard's whole navigation
  // surface (press-only mode, RoutePressable, etc).
  const trimmedScientificName = scientificName?.trim();
  const scientificSegment = trimmedScientificName
    ? toKebabCase(trimmedScientificName)
    : '';
  const hasValidTaxonId =
    typeof taxonId === 'string' && taxonId.trim().length > 0;
  const canLinkToTaxon = hasValidTaxonId && Boolean(scientificSegment);
  const taxonHref: Href | undefined = canLinkToTaxon
    ? ({
        pathname: '/species/[...identifier]',
        params: { identifier: [taxonId, scientificSegment] },
      } as Href)
    : undefined;
  const taxonHrefPath = canLinkToTaxon
    ? `/species/${taxonId}/${scientificSegment}`
    : undefined;

  const content = (
    <View
      collapsable={false}
      style={[styles.container, { width: imageSize }, style]}
    >
      <View
        testID='observation-card-image-wrapper'
        style={[
          styles.imageWrapper,
          { width: imageSize, height: imageSize },
          !imageUrl && { backgroundColor: placeholderBackground },
        ]}
      >
        {imageUrl ? (
          <Image
            testID='observation-card-image'
            source={{ uri: imageUrl }}
            style={styles.image}
            resizeMode='cover'
            accessibilityLabel={`Observation #${catalogNumber}`}
          />
        ) : (
          <View
            style={[
              styles.placeholder,
              { backgroundColor: placeholderBackground },
            ]}
            testID='observation-card-placeholder'
          >
            <IconImage size='20' color={placeholderIcon} />
          </View>
        )}
      </View>

      <View style={styles.textSection}>
        {scientificName ? (
          taxonHref ? (
            <RoutePressable
              href={taxonHref}
              hrefPath={taxonHrefPath}
              accessibilityRole='link'
            >
              <ThemedText
                variant='bodySmallEmphasis'
                numberOfLines={1}
                style={linkStyle}
              >
                {scientificName}
              </ThemedText>
            </RoutePressable>
          ) : (
            <ThemedText variant='bodySmallEmphasis' numberOfLines={1}>
              {scientificName}
            </ThemedText>
          )
        ) : null}
        {inatUrl ? (
          <ThemedText
            variant='bodySmallEmphasis'
            numberOfLines={1}
            style={linkStyle}
            accessibilityRole='link'
            onPress={() => Linking.openURL(inatUrl)}
          >
            {`#${catalogNumber}`}
          </ThemedText>
        ) : (
          <ThemedText variant='bodySmallEmphasis' numberOfLines={1}>
            {`#${catalogNumber}`}
          </ThemedText>
        )}
        {varLabel ? (
          <View style={styles.valueRow}>
            {varColor ? (
              varShape && isShapeKey(varShape) ? (
                <View testID='observation-card-shape'>
                  <ShapeMarker shape={varShape} color={varColor} size={8} />
                </View>
              ) : (
                <View
                  testID='observation-card-dot'
                  style={[styles.dot, { backgroundColor: varColor }]}
                />
              )
            ) : null}
            <ThemedText variant='bodySmall' numberOfLines={1}>
              {varLabel}
            </ThemedText>
          </View>
        ) : (
          <ThemedText
            variant='bodySmall'
            numberOfLines={1}
            style={{ color: palette.text.disabled.default }}
          >
            No data
          </ThemedText>
        )}
        {attribution || license ? (
          <View style={styles.creditRow} testID='observation-card-credit'>
            <ThemedText
              variant='bodySmall'
              numberOfLines={1}
              style={{ color: palette.text.default.tertiary }}
            >
              {attribution || ' '}
            </ThemedText>
            {license ? (
              licenseUrl ? (
                <ThemedText
                  variant='bodySmallLink'
                  numberOfLines={1}
                  onPress={() => Linking.openURL(licenseUrl)}
                >
                  {license}
                </ThemedText>
              ) : (
                <ThemedText
                  variant='bodySmall'
                  numberOfLines={1}
                  style={{ color: palette.text.default.tertiary }}
                >
                  {license}
                </ThemedText>
              )
            ) : (
              <ThemedText
                variant='bodySmall'
                style={{ color: palette.text.default.tertiary }}
              >
                {' '}
              </ThemedText>
            )}
          </View>
        ) : (
          <View style={styles.creditRow} testID='observation-card-credit'>
            <ThemedText
              variant='bodySmall'
              numberOfLines={1}
              style={{ color: palette.text.disabled.default }}
            >
              No media
            </ThemedText>
            <ThemedText
              variant='bodySmall'
              style={{ color: palette.text.default.tertiary }}
            >
              {' '}
            </ThemedText>
          </View>
        )}
      </View>
    </View>
  );

  if (onPress) {
    return (
      <Pressable
        onPress={onPress}
        accessibilityRole='button'
        accessibilityLabel={`Observation #${catalogNumber}`}
        testID={testID}
      >
        {content}
      </Pressable>
    );
  }

  return (
    <View testID={testID} collapsable={false}>
      {content}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    gap: Size.space['150'],
  },
  imageWrapper: {
    borderRadius: Size.radius['200'],
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  placeholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textSection: {
    gap: Size.space['100'],
  },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Size.space['100'],
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  creditRow: {
    flexDirection: 'column',
  },
});
