// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import type {
  DataSource,
  EnvironmentVariableDefinition,
  LocationSearchResult,
} from '@/data/types';

export type LocalSourceMeta = {
  source: 'upload-local';
  uploadedAt: string;
  warnings?: string[];
};

export type RawRecord = Record<string, unknown>;

export type UploadedCategoricalStatsRow = {
  variable: string;
  variableCategory?: string | null;
  metric: string;
  metricLabel?: string | null;
  value: number;
};

export type UploadedCategoricalValueLookupRow = {
  variable: string;
  variableName?: string | null;
  variableCategory?: string | null;
  code: string;
  metric: string;
  label?: string | null;
  description?: string | null;
  group?: string | null;
  groupLabel?: string | null;
};

export type UploadedDensityGraphPoint = {
  variable: string;
  variableCategory?: string | null;
  value: number;
  density: number;
};

export type UploadedOccurrenceRow = {
  catalogNumber: number | string;
  latitude: number;
  longitude: number;
  locationGid?: string | null;
  catalogName?: string | null;
  catalogAutoGenerated?: boolean;
  /** Raw values for columns that are members of a ternary composition group
   * (e.g. sand/silt/clay), keyed by column id — kept separately from the rest
   * of the raw row (which is otherwise dropped) so a location-filtered scope
   * can still recompute the joint composition density. */
  compositionValues?: Record<string, number>;
};

export type UploadedOccurrenceIndexRow = {
  variable: string;
  mode: 'range' | 'category';
  min?: number;
  max?: number;
  classValue?: number | string;
  observationIds: (number | string)[];
};

export type UploadedSummaryStatsRow = {
  variable: string;
  variableCategory?: string | null;
  variableName?: string;
  units?: string | null;
  variableType?: string | null;
  domain?: string | null;
  count: number;
  min: number | null;
  mean: number | null;
  max: number | null;
  median?: number | null;
  std?: number | null;
  stddev?: number | null;
  variance?: number | null;
  range?: number | null;
  q01?: number | null;
  q10?: number | null;
  q25?: number | null;
  q75?: number | null;
  q90?: number | null;
  q99?: number | null;
  iqr?: number | null;
  q10_90_range?: number | null;
  bins?: number[];
  counts?: number[];
  circular_mean?: number | null;
  rbar?: number | null;
  circular_std?: number | null;
  circular_var?: number | null;
  unique_classes?: number | null;
  entropy?: number | null;
  mode?: string | number | null;
};

export type RawCategoricalStatsRow = {
  variable?: unknown;
  variableName?: unknown;
  variableCategory?: unknown;
  metric?: unknown;
  metricLabel?: unknown;
  value?: unknown;
};

export type RawDensityGraphRow = {
  variable?: unknown;
  variableName?: unknown;
  variableCategory?: unknown;
  points?: unknown;
  density?: unknown;
};

export type RawCategoricalValueLookupRow = {
  variable?: unknown;
  variableName?: unknown;
  variableCategory?: unknown;
  code?: unknown;
  metric?: unknown;
  label?: unknown;
  description?: unknown;
  group?: unknown;
  groupLabel?: unknown;
};

export type RawOccurrenceRow = {
  [key: string]: unknown;
  catalogNumber?: unknown;
  decimalLatitude?: unknown;
  decimalLongitude?: unknown;
  locationGid?: unknown;
  observationName?: unknown;
};

export type RawOccurrenceIndexRow = RawRecord;

export type RawSummaryStatsRow = {
  variable?: unknown;
  variableName?: unknown;
  variable_name?: unknown;
  variableCategory?: unknown;
  units?: unknown;
  variableType?: unknown;
  circular_mean?: unknown;
  rbar?: unknown;
  circular_std?: unknown;
  circular_var?: unknown;
  variable_type?: unknown;
  valueType?: unknown;
  value_type?: unknown;
  domain?: unknown;
  count?: unknown;
  min?: unknown;
  mean?: unknown;
  max?: unknown;
  median?: unknown;
  std?: unknown;
  variance?: unknown;
  range?: unknown;
  iqr?: unknown;
  ['10th percentile']?: unknown;
  ['25th percentile']?: unknown;
  ['75th percentile']?: unknown;
  ['90th percentile']?: unknown;
  ['10_90_range']?: unknown;
  ['10th_percentile']?: unknown;
  ['25th_percentile']?: unknown;
  ['75th_percentile']?: unknown;
  ['90th_percentile']?: unknown;
  entropy?: unknown;
  mode?: unknown;
};

export type RawVariableMetadataRow = {
  name?: unknown;
  exportedName?: unknown;
  exported_name?: unknown;
  variable?: unknown;
  id?: unknown;
  category?: unknown;
  units?: unknown;
  valueType?: unknown;
  value_type?: unknown;
  source_ids?: unknown;
  domain?: unknown;
  group?: unknown;
  group_label?: unknown;
  sort_order?: unknown;
  render_min?: unknown;
  render_max?: unknown;
  legend_classes?: unknown;
  composition_group?: unknown;
  compositionGroup?: unknown;
  composition_axis?: unknown;
  compositionAxis?: unknown;
  composition_label?: unknown;
  compositionLabel?: unknown;
};

export type RawDensityGridRow = {
  variable?: unknown;
  resolution?: unknown;
  density?: unknown;
  sample_a?: unknown;
  sample_b?: unknown;
  sample_c?: unknown;
  class_ids?: unknown;
  class_boundary_a?: unknown;
  class_boundary_b?: unknown;
};

export type UploadedDensityGridRow = {
  variable: string;
  resolution: number;
  density: number[];
  sampleA: number[];
  sampleB: number[];
  sampleC: number[];
  classIds?: number[] | null;
  classBoundaryA?: number[] | null;
  classBoundaryB?: number[] | null;
};

export type RawLocationRow = {
  gid?: unknown;
  name?: unknown;
  level?: unknown;
  hierarchy?: unknown;
};

export type RawUploadedParquetBundle = {
  categoricalStats: RawCategoricalStatsRow[];
  ordinalStats?: RawCategoricalStatsRow[];
  circularStats?: RawSummaryStatsRow[];
  categoricalValueLookup?: RawCategoricalValueLookupRow[];
  densityGraph: RawDensityGraphRow[];
  densityGrid?: RawDensityGridRow[];
  occurrences: RawOccurrenceRow[];
  occurrenceIndex: RawOccurrenceIndexRow[];
  summaryStats: RawSummaryStatsRow[];
  variableMetadata?: RawVariableMetadataRow[];
  variableDefinitions?: EnvironmentVariableDefinition[];
  dataSources?: Record<string, DataSource>;
  locations?: RawLocationRow[];
  meta?: LocalSourceMeta;
};

export type UploadedParquetBundle = {
  categoricalStats: UploadedCategoricalStatsRow[];
  ordinalStats: UploadedCategoricalStatsRow[];
  categoricalValueLookup?: UploadedCategoricalValueLookupRow[];
  densityGraph: UploadedDensityGraphPoint[];
  densityGrid?: UploadedDensityGridRow[];
  occurrences: UploadedOccurrenceRow[];
  occurrenceIndex: UploadedOccurrenceIndexRow[];
  summaryStats: UploadedSummaryStatsRow[];
  variableDefinitions?: EnvironmentVariableDefinition[];
  dataSources?: Record<string, DataSource>;
  locations?: LocationSearchResult[];
  meta?: LocalSourceMeta;
};

export class UploadedParquetBundleValidationError extends Error {
  issues: string[];

  constructor(issues: string[]) {
    super(`Uploaded parquet bundle is invalid: ${issues.join(' | ')}`);
    this.name = 'UploadedParquetBundleValidationError';
    this.issues = issues;
  }
}
