// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import {
  createSpeciesDataSource,
  type SpeciesDataSource,
} from '@/data/speciesDataSource';
import type {
  LocationSearchResult,
  SpeciesEnvironmentCategorySampleResponse,
  SpeciesEnvironmentObservation,
  SpeciesEnvironmentSliceResponse,
  SpeciesEnvironmentStats,
  SpeciesOccurrence,
} from '@/data/types';
import { isCategoricalAggregateMetric } from '@/data/uploadLocalSpeciesDataSource.shared';
import { validateUploadedParquetBundle } from '@/data/uploadLocalSpeciesDataSource.normalize';
import {
  applyConv,
  getMetricToImperial,
  reverseConv,
  type LinearConversion,
} from '@/data/unitConversions';
import type {
  UploadedCategoricalStatsRow,
  UploadedDensityGraphPoint,
  UploadedOccurrenceIndexRow,
  UploadedOccurrenceRow,
  UploadedParquetBundle,
  UploadedSummaryStatsRow,
} from '@/data/uploadLocalSpeciesDataSource.types';

type BuildLocalSpeciesDataSourceOptions = {
  bundle: UploadedParquetBundle;
  speciesId?: number;
};

const DEFAULT_SPECIES_ID = 0;
const LOCATION_LEVEL_TO_NUMBER: Record<string, number> = {
  continent: -1,
  country: 0,
  state: 1,
  county: 2,
};

const normalizeLocationLevel = (level: string | number | undefined) => {
  if (typeof level === 'number') {
    return level;
  }

  if (typeof level === 'string') {
    return LOCATION_LEVEL_TO_NUMBER[level.toLowerCase()];
  }

  return undefined;
};

const normalizeLocationToken = (value: string | null | undefined) => {
  return typeof value === 'string' ? value.trim().toLowerCase() : '';
};

const findLocationsByNameToken = (
  normalizedName: string,
  locationLookup: ReturnType<typeof buildLocationLookupMaps>,
) => {
  if (!normalizedName) {
    return [] as LocationSearchResult[];
  }

  return Array.from(locationLookup.byGid.values()).filter(
    (location) => normalizeLocationToken(location.name) === normalizedName,
  );
};

const buildLocationLookupMaps = (locations: LocationSearchResult[]) => {
  const byGid = new Map<string, LocationSearchResult>();
  const byName = new Map<string, LocationSearchResult>();

  locations.forEach((location) => {
    const normalizedGid = normalizeLocationToken(location.gid);
    const normalizedName = normalizeLocationToken(location.name);

    if (normalizedGid) {
      byGid.set(normalizedGid, location);
    }

    if (normalizedName && !byName.has(normalizedName)) {
      byName.set(normalizedName, location);
    }
  });

  return { byGid, byName };
};

const resolveLocationEntry = (
  token: string | null | undefined,
  locationLookup: ReturnType<typeof buildLocationLookupMaps>,
) => {
  const normalizedToken = normalizeLocationToken(token);
  if (!normalizedToken) {
    return null;
  }

  return (
    locationLookup.byGid.get(normalizedToken) ??
    locationLookup.byName.get(normalizedToken) ??
    null
  );
};

const buildScopeTokens = (
  token: string,
  locationLookup: ReturnType<typeof buildLocationLookupMaps>,
) => {
  const normalizedToken = normalizeLocationToken(token);
  const resolvedByGid = locationLookup.byGid.get(normalizedToken);
  const matchingEntriesByName = resolvedByGid
    ? []
    : findLocationsByNameToken(normalizedToken, locationLookup);

  return new Set(
    resolvedByGid
      ? [
          normalizeLocationToken(resolvedByGid.gid),
          normalizeLocationToken(resolvedByGid.name),
        ].filter(Boolean)
      : [
          normalizedToken,
          ...matchingEntriesByName.map((location) =>
            normalizeLocationToken(location.gid),
          ),
        ].filter(Boolean),
  );
};

const matchesParentLocation = (
  location: { gid: string; name: string; hierarchy: string[] },
  parent: string,
  locationLookup: ReturnType<typeof buildLocationLookupMaps>,
) => {
  const scopeTokens = buildScopeTokens(parent, locationLookup);
  if (!scopeTokens.size) {
    return true;
  }

  if (scopeTokens.has(normalizeLocationToken(location.gid))) {
    return true;
  }

  return location.hierarchy.some((entry) => {
    const normalizedEntry = normalizeLocationToken(entry);
    return scopeTokens.has(normalizedEntry);
  });
};

const toSpeciesOccurrences = (
  rows: UploadedOccurrenceRow[],
): SpeciesOccurrence[] => {
  return rows
    .filter(
      (row) => Number.isFinite(row.latitude) && Number.isFinite(row.longitude),
    )
    .map((row) => ({
      catalogNumber: row.catalogNumber,
      latitude: row.latitude,
      longitude: row.longitude,
      catalogAutoGenerated: row.catalogAutoGenerated ?? false,
    }));
};

const buildStatsByVariable = (
  bundle: UploadedParquetBundle,
  speciesId: number,
): Record<string, SpeciesEnvironmentStats> => {
  const summaryByVariable = bundle.summaryStats.reduce<
    Record<string, UploadedSummaryStatsRow>
  >((acc, row) => {
    acc[row.variable] = row;
    return acc;
  }, {});

  const densityByVariable = bundle.densityGraph.reduce<
    Record<string, UploadedDensityGraphPoint[]>
  >((acc, row) => {
    if (!acc[row.variable]) {
      acc[row.variable] = [];
    }
    acc[row.variable].push(row);
    return acc;
  }, {});

  const categoricalByVariable = bundle.categoricalStats.reduce<
    Record<string, UploadedCategoricalStatsRow[]>
  >((acc, row) => {
    if (!acc[row.variable]) {
      acc[row.variable] = [];
    }
    acc[row.variable].push(row);
    return acc;
  }, {});

  const ordinalByVariable = bundle.ordinalStats.reduce<
    Record<string, UploadedCategoricalStatsRow[]>
  >((acc, row) => {
    if (!acc[row.variable]) {
      acc[row.variable] = [];
    }
    acc[row.variable].push(row);
    return acc;
  }, {});

  const categoricalLookupByVariableAndMetric = (
    bundle.categoricalValueLookup ?? []
  ).reduce<
    Record<
      string,
      Record<string, { label?: string | null; description?: string | null }>
    >
  >((acc, row) => {
    if (!acc[row.variable]) {
      acc[row.variable] = {};
    }
    acc[row.variable][row.metric] = {
      label: row.label,
      description: row.description,
    };
    return acc;
  }, {});

  const variableDefinitionsById = new Map(
    (bundle.variableDefinitions ?? []).map((definition) => [
      definition.id,
      definition,
    ]),
  );

  const variableIds = new Set<string>([
    ...Object.keys(summaryByVariable),
    ...Object.keys(densityByVariable),
    ...Object.keys(categoricalByVariable),
    ...Object.keys(ordinalByVariable),
  ]);

  return Array.from(variableIds).reduce<
    Record<string, SpeciesEnvironmentStats>
  >((acc, variable) => {
    const summaryRow = summaryByVariable[variable];
    const variableDefinition = variableDefinitionsById.get(variable);
    const densityRows = densityByVariable[variable] ?? [];

    // Ordinal path: class_id-sorted distribution + quantile stats from tall rows.
    const ordinalRows = ordinalByVariable[variable];
    if (ordinalRows) {
      const ordinalLookupByMetric = categoricalLookupByVariableAndMetric[variable] ?? {};
      const metricVal = (m: string) => ordinalRows.find((r) => r.metric === m)?.value ?? null;
      const totalSamples = metricVal('total_samples');
      const classRows = ordinalRows
        .filter((r) => r.metric.startsWith('class_'))
        .map((r) => {
          const classId = parseInt(r.metric.slice(6), 10);
          const fraction = r.value;
          const count = typeof totalSamples === 'number' ? Math.round(totalSamples * fraction) : 0;
          const lookupEntry = ordinalLookupByMetric[r.metric];
          const legendClass = variableDefinition?.legendClasses?.find(
            (cls) => String(cls.id) === String(classId),
          );
          return {
            value: r.metric,
            className: r.metricLabel ?? lookupEntry?.label ?? r.metric,
            description: lookupEntry?.description ?? null,
            color: legendClass?.color ?? null,
            count,
            fraction,
            classId,
          };
        })
        .sort((a, b) => a.classId - b.classId)
        .map(({ classId: _cid, ...rest }) => rest);

      acc[variable] = {
        speciesId,
        variable,
        variableName: summaryRow?.variableName ?? variableDefinition?.name ?? variable,
        units: summaryRow?.units ?? variableDefinition?.units ?? null,
        variableType: 'ordinal',
        summary: {
          count: typeof totalSamples === 'number' ? Math.round(totalSamples) : (summaryRow?.count ?? 0),
          min: null,
          mean: null,
          max: null,
          median: metricVal('median'),
          std: null,
          stddev: null,
          variance: null,
          range: null,
          q01: null,
          q10: metricVal('10th_percentile'),
          q25: metricVal('25th_percentile'),
          q75: metricVal('75th_percentile'),
          q90: metricVal('90th_percentile'),
          q99: null,
          iqr: null,
          q10_90_range: null,
          circular_mean: null,
          rbar: null,
          circular_std: null,
          circular_var: null,
          unique_classes: metricVal('unique_classes'),
          entropy: metricVal('entropy'),
          mode: metricVal('mode'),
        },
        histogram: null,
        densityCurve: null,
        categoricalDistribution: classRows,
      };
      return acc;
    }

    const categoryRows = categoricalByVariable[variable] ?? [];
    const categoryLookupByMetric =
      categoricalLookupByVariableAndMetric[variable] ?? {};
    const totalSamplesRow = categoryRows.find(
      (entry) => entry.metric === 'total_samples',
    );
    const totalSamples =
      totalSamplesRow && Number.isFinite(totalSamplesRow.value)
        ? totalSamplesRow.value
        : null;
    const uniqueClassesRow = categoryRows.find(
      (entry) => entry.metric === 'unique_classes',
    );
    const entropyRow = categoryRows.find((entry) => entry.metric === 'entropy');
    const modeRow = categoryRows.find((entry) => entry.metric === 'mode');
    const classRows = categoryRows.filter(
      (entry) => !isCategoricalAggregateMetric(entry.metric),
    );
    const isCategoricalVariable = classRows.length > 0;

    // Build metric→code map so we can look up legend class colors by numeric id.
    const metricToCode = Object.fromEntries(
      (bundle.categoricalValueLookup ?? [])
        .filter((row) => row.variable === variable)
        .map((row) => [row.metric, row.code]),
    );
    // Reverse map: code → metric name, for resolving aggregate values like mode.
    const codeToMetric = new Map<string, string>();
    for (const [metric, code] of Object.entries(metricToCode)) {
      codeToMetric.set(String(code).trim(), metric);
      const num = Number(code);
      if (Number.isFinite(num)) {
        codeToMetric.set(String(Math.trunc(num)), metric);
      }
    }

    const categoricalDistribution = classRows
      .filter((entry) => Number.isFinite(entry.value))
      .map((entry) => {
        const fraction = entry.value;
        const count =
          typeof totalSamples === 'number' && Number.isFinite(totalSamples)
            ? Math.round(totalSamples * fraction)
            : 0;

        const code = metricToCode[entry.metric];
        const legendClass = code
          ? variableDefinition?.legendClasses?.find(
              (cls) => String(cls.id) === code,
            )
          : null;

        return {
          value: entry.metric,
          className:
            entry.metricLabel ??
            categoryLookupByMetric[entry.metric]?.label ??
            entry.metric,
          description:
            categoryLookupByMetric[entry.metric]?.description ?? null,
          color: legendClass?.color ?? null,
          count,
          fraction,
        };
      });

    const inferredCount =
      typeof totalSamples === 'number' && Number.isFinite(totalSamples)
        ? Math.max(0, Math.round(totalSamples))
        : categoricalDistribution.reduce(
            (sum, entry) =>
              sum + (Number.isFinite(entry.count) ? entry.count : 0),
            0,
          );

    acc[variable] = {
      speciesId,
      variable,
      variableName:
        summaryRow?.variableName ?? variableDefinition?.name ?? variable,
      units: summaryRow?.units ?? variableDefinition?.units ?? null,
      variableType:
        summaryRow?.variableType ??
        variableDefinition?.valueType ??
        (isCategoricalVariable ? 'categorical' : null),
      summary: {
        count: summaryRow?.count ?? inferredCount,
        min: summaryRow?.min ?? null,
        mean: summaryRow?.mean ?? null,
        max: summaryRow?.max ?? null,
        median: summaryRow?.median ?? null,
        std: summaryRow?.std ?? null,
        stddev: summaryRow?.stddev ?? null,
        variance: summaryRow?.variance ?? null,
        range: summaryRow?.range ?? null,
        q01: summaryRow?.q01 ?? null,
        q10: summaryRow?.q10 ?? null,
        q25: summaryRow?.q25 ?? null,
        q75: summaryRow?.q75 ?? null,
        q90: summaryRow?.q90 ?? null,
        q99: summaryRow?.q99 ?? null,
        iqr: summaryRow?.iqr ?? null,
        q10_90_range: summaryRow?.q10_90_range ?? null,
        circular_mean: summaryRow?.circular_mean ?? null,
        rbar: summaryRow?.rbar ?? null,
        circular_std: summaryRow?.circular_std ?? null,
        circular_var: summaryRow?.circular_var ?? null,
        unique_classes:
          summaryRow?.unique_classes ??
          (uniqueClassesRow && Number.isFinite(uniqueClassesRow.value)
            ? uniqueClassesRow.value
            : null),
        entropy:
          summaryRow?.entropy ??
          (entropyRow && Number.isFinite(entropyRow.value)
            ? entropyRow.value
            : null),
        mode: (() => {
          if (summaryRow?.mode != null) return summaryRow.mode;
          if (modeRow == null) return null;
          const raw = String(modeRow.value).trim();
          const trunc = String(Math.trunc(modeRow.value));
          return codeToMetric.get(raw) ?? codeToMetric.get(trunc) ?? raw;
        })(),
      },
      histogram:
        Array.isArray(summaryRow?.bins) && Array.isArray(summaryRow?.counts)
          ? {
              bins: summaryRow.bins,
              counts: summaryRow.counts,
            }
          : null,
      densityCurve:
        densityRows.length > 0
          ? {
              points: densityRows.map((point) => point.value),
              density: densityRows.map((point) => point.density),
            }
          : null,
      categoricalDistribution,
    };
    return acc;
  }, {});
};

const collectCatalogsForRange = (
  indexRows: UploadedOccurrenceIndexRow[],
  min: number,
  max: number,
) => {
  const catalogs = indexRows
    .filter((row) => row.mode === 'range')
    .filter((row) => typeof row.min === 'number' && typeof row.max === 'number')
    .filter((row) => (row.max as number) >= min && (row.min as number) <= max)
    .flatMap((row) => row.observationIds);

  return Array.from(new Set(catalogs.map((id) => String(id))));
};

const collectCatalogsForCategory = (
  indexRows: UploadedOccurrenceIndexRow[],
  classValue: string | number,
) => {
  const normalizedClassValue = String(classValue);
  const catalogs = indexRows
    .filter((row) => row.mode === 'category')
    .filter((row) => String(row.classValue) === normalizedClassValue)
    .flatMap((row) => row.observationIds);

  return Array.from(new Set(catalogs.map((id) => String(id))));
};

const findObservationEnvironmentValue = (
  indexRows: UploadedOccurrenceIndexRow[],
  catalogNumber: string | number,
) => {
  const targetCatalog = String(catalogNumber);
  const matchedRow = indexRows.find((row) =>
    row.observationIds.some((id) => String(id) === targetCatalog),
  );

  if (!matchedRow) {
    return null;
  }

  if (matchedRow.mode === 'category') {
    return matchedRow.classValue ?? null;
  }

  return typeof matchedRow.min === 'number' ? matchedRow.min : null;
};

const findCategoricalDistributionEntry = (
  stats: SpeciesEnvironmentStats | undefined,
  value: string | number | null,
) => {
  if (!stats?.categoricalDistribution || value === null) {
    return null;
  }

  const normalizedValue = String(value);
  return (
    stats.categoricalDistribution.find(
      (entry) => String(entry.value) === normalizedValue,
    ) ?? null
  );
};

const toObservationsByCatalog = (rows: UploadedOccurrenceRow[]) => {
  return rows.reduce<Record<string, UploadedOccurrenceRow>>((acc, row) => {
    acc[String(row.catalogNumber)] = row;
    return acc;
  }, {});
};

const groupIndexRowsByVariable = (rows: UploadedOccurrenceIndexRow[]) => {
  return rows.reduce<Record<string, UploadedOccurrenceIndexRow[]>>(
    (acc, row) => {
      if (!acc[row.variable]) {
        acc[row.variable] = [];
      }
      acc[row.variable].push(row);
      return acc;
    },
    {},
  );
};

const matchesObservationLocation = (
  rowLocationGid: string | null | undefined,
  locationLookup: ReturnType<typeof buildLocationLookupMaps>,
  locationGid?: string | null,
) => {
  if (!locationGid) {
    return true;
  }

  if (!rowLocationGid) {
    return false;
  }

  const rowLocation = resolveLocationEntry(rowLocationGid, locationLookup);
  if (!rowLocation) {
    return (
      normalizeLocationToken(rowLocationGid) ===
      normalizeLocationToken(locationGid)
    );
  }

  return matchesParentLocation(rowLocation, locationGid, locationLookup);
};

const filterCatalogIdsByLocation = (
  catalogIds: (number | string)[],
  observationsByCatalog: Record<string, UploadedOccurrenceRow>,
  locationLookup: ReturnType<typeof buildLocationLookupMaps>,
  locationGid?: string | null,
) => {
  if (!locationGid) {
    return catalogIds;
  }

  return catalogIds.filter((id) => {
    const rowLocationGid = observationsByCatalog[String(id)]?.locationGid;
    return matchesObservationLocation(
      rowLocationGid,
      locationLookup,
      locationGid,
    );
  });
};

const toSortedNumericValues = (values: number[]) =>
  values.slice().sort((left, right) => left - right);

const quantileFromSortedValues = (values: number[], quantile: number) => {
  if (!values.length) {
    return null;
  }

  const clamped = Math.min(1, Math.max(0, quantile));
  const position = (values.length - 1) * clamped;
  const lowerIndex = Math.floor(position);
  const upperIndex = Math.ceil(position);

  if (lowerIndex === upperIndex) {
    return values[lowerIndex];
  }

  const weight = position - lowerIndex;
  return values[lowerIndex] * (1 - weight) + values[upperIndex] * weight;
};

const buildHistogramFromValues = (
  values: number[],
  desiredBucketCount?: number,
) => {
  if (!values.length) {
    return null;
  }

  const sortedValues = toSortedNumericValues(values);
  const min = sortedValues[0];
  const max = sortedValues[sortedValues.length - 1];
  if (min === max) {
    const spread = Math.max(Math.abs(min) * 0.01, 1e-6);
    return {
      bins: [min - spread, min + spread],
      counts: [sortedValues.length],
    };
  }

  const bucketCount = Math.max(
    1,
    desiredBucketCount ??
      Math.min(12, Math.ceil(Math.sqrt(sortedValues.length))),
  );
  const span = max - min;
  const step = span / bucketCount;
  const bins = Array.from(
    { length: bucketCount + 1 },
    (_, index) => min + step * index,
  );
  const counts = Array.from({ length: bucketCount }, () => 0);

  sortedValues.forEach((value) => {
    const rawIndex = Math.floor(((value - min) / span) * bucketCount);
    const index = Math.min(bucketCount - 1, Math.max(0, rawIndex));
    counts[index] += 1;
  });

  return { bins, counts };
};

const KDE_N_POINTS = 128;
const INV_SQRT_2PI = 1 / Math.sqrt(2 * Math.PI);

const buildGaussianKde = (
  sortedValues: number[],
): { points: number[]; density: number[] } | null => {
  const n = sortedValues.length;
  if (n < 2) return null;

  let minVal = sortedValues[0];
  let maxVal = sortedValues[n - 1];
  if (Math.abs(maxVal - minVal) < 1e-10) {
    const span = Math.abs(minVal) * 0.1 || 1.0;
    minVal -= span;
    maxVal += span;
  }

  const mean = sortedValues.reduce((s, v) => s + v, 0) / n;
  const variance = sortedValues.reduce((s, v) => s + (v - mean) ** 2, 0) / (n - 1);
  const std = Math.sqrt(variance);

  const h = std < 1e-10
    ? (Math.abs(sortedValues[0]) * 0.01 || 0.1)
    : 1.06 * std * Math.pow(n, -0.2);

  const step = (maxVal - minVal) / (KDE_N_POINTS - 1);
  const points: number[] = [];
  const density: number[] = [];

  for (let i = 0; i < KDE_N_POINTS; i++) {
    const x = minVal + i * step;
    let sum = 0;
    for (let j = 0; j < n; j++) {
      const u = (x - sortedValues[j]) / h;
      sum += INV_SQRT_2PI * Math.exp(-0.5 * u * u);
    }
    points.push(x);
    density.push(sum / (n * h));
  }

  return { points, density };
};

// Wrapped Gaussian KDE for circular variables (degrees, [0,360)).
// Matches the backend's _von_mises_kde_curve bandwidth and grid.
const buildCircularKde = (
  values: number[],
): { points: number[]; density: number[] } | null => {
  const n = values.length;
  if (n < 2) return null;

  // Circular std via mean resultant length R
  let sinSum = 0;
  let cosSum = 0;
  for (const v of values) {
    const r = (v * Math.PI) / 180;
    sinSum += Math.sin(r);
    cosSum += Math.cos(r);
  }
  const R = Math.sqrt(sinSum * sinSum + cosSum * cosSum) / n;
  const cstdRad = Math.sqrt(-2 * Math.log(Math.max(R, 1e-10)));
  if (!isFinite(cstdRad) || cstdRad < 1e-6) return null;

  const hRad = Math.max(Math.pow(4 / (3 * n), 0.2) * cstdRad, 0.05);

  const points: number[] = [];
  const density: number[] = [];
  const TWO_PI = 2 * Math.PI;

  for (let i = 0; i < KDE_N_POINTS; i++) {
    const xDeg = (i / KDE_N_POINTS) * 360;
    const xRad = (xDeg * Math.PI) / 180;
    let sum = 0;
    for (const vDeg of values) {
      const vRad = (vDeg * Math.PI) / 180;
      // Wrap difference to [-π, π]
      let d = xRad - vRad;
      d -= TWO_PI * Math.round(d / TWO_PI);
      const u = d / hRad;
      sum += INV_SQRT_2PI * Math.exp(-0.5 * u * u);
    }
    points.push(xDeg);
    density.push(sum / (n * hRad));
  }

  // Normalize so integral over [0, 2π) ≈ 1
  const stepRad = TWO_PI / KDE_N_POINTS;
  const area = density.reduce((s, d) => s + d, 0) * stepRad;
  if (area > 0) {
    for (let i = 0; i < density.length; i++) density[i] /= area;
  }

  return { points, density };
};

const buildScopedCategoricalStats = ({
  stats,
  locationGid,
  observationsByCatalog,
  locationLookup,
  indexRows,
}: {
  stats: SpeciesEnvironmentStats;
  locationGid: string;
  observationsByCatalog: Record<string, UploadedOccurrenceRow>;
  locationLookup: ReturnType<typeof buildLocationLookupMaps>;
  indexRows: UploadedOccurrenceIndexRow[];
}): SpeciesEnvironmentStats => {
  const countsByClass = new Map<string, number>();
  let totalCount = 0;

  indexRows
    .filter((row) => row.mode === 'category')
    .forEach((row) => {
      const scopedObservationIds = filterCatalogIdsByLocation(
        row.observationIds,
        observationsByCatalog,
        locationLookup,
        locationGid,
      );
      if (!scopedObservationIds.length) {
        return;
      }

      const classKey = String(row.classValue ?? '');
      countsByClass.set(
        classKey,
        (countsByClass.get(classKey) ?? 0) + scopedObservationIds.length,
      );
      totalCount += scopedObservationIds.length;
    });

  const baselineDistribution = stats.categoricalDistribution ?? [];
  const categoricalDistribution = Array.from(countsByClass.entries())
    .map(([classValue, count]) => {
      const baseline = baselineDistribution.find(
        (entry) => String(entry.value) === classValue,
      );
      return {
        value: baseline?.value ?? classValue,
        className: baseline?.className ?? classValue,
        description: baseline?.description ?? null,
        color: baseline?.color ?? null,
        count,
        fraction: totalCount > 0 ? count / totalCount : 0,
      };
    })
    .sort((left, right) => right.count - left.count);

  // Compute entropy and mode from filtered distribution
  let entropy: number | null = null;
  let mode: string | null = null;
  if (totalCount > 0) {
    let entropySum = 0;
    let maxCount = -1;
    for (const [classKey, cnt] of countsByClass.entries()) {
      const p = cnt / totalCount;
      if (p > 0) entropySum -= p * Math.log(p);
      if (cnt > maxCount) {
        maxCount = cnt;
        mode = classKey;
      }
    }
    entropy = entropySum;
  }

  return {
    ...stats,
    summary: {
      count: totalCount,
      min: null,
      mean: null,
      max: null,
      stddev: null,
      q01: null,
      q10: null,
      q90: null,
      q99: null,
      entropy,
      unique_classes: countsByClass.size || null,
      mode,
    },
    categoricalDistribution,
    baselineSummary: stats.summary,
    baselineCategoricalDistribution: baselineDistribution,
  };
};

const buildScopedNumericStats = ({
  stats,
  locationGid,
  observationsByCatalog,
  locationLookup,
  indexRows,
}: {
  stats: SpeciesEnvironmentStats;
  locationGid: string;
  observationsByCatalog: Record<string, UploadedOccurrenceRow>;
  locationLookup: ReturnType<typeof buildLocationLookupMaps>;
  indexRows: UploadedOccurrenceIndexRow[];
}): SpeciesEnvironmentStats => {
  const scopedValues = indexRows
    .filter((row) => row.mode === 'range')
    .flatMap((row) => {
      if (typeof row.min !== 'number' || typeof row.max !== 'number') {
        return [];
      }

      const scopedObservationIds = filterCatalogIdsByLocation(
        row.observationIds,
        observationsByCatalog,
        locationLookup,
        locationGid,
      );
      if (!scopedObservationIds.length) {
        return [];
      }

      const value = row.min === row.max ? row.min : (row.min + row.max) / 2;
      return scopedObservationIds.map(() => value);
    });

  const sortedValues = toSortedNumericValues(scopedValues);
  const count = sortedValues.length;
  const min = count ? sortedValues[0] : null;
  const max = count ? sortedValues[count - 1] : null;
  const mean = count
    ? sortedValues.reduce((sum, value) => sum + value, 0) / count
    : null;
  const variance =
    count > 0 && mean !== null
      ? sortedValues.reduce((sum, value) => sum + (value - mean) ** 2, 0) /
        count
      : null;
  const histogram = buildHistogramFromValues(
    sortedValues,
    stats.histogram?.counts.length,
  );

  let circular_mean: number | null = null;
  let rbar: number | null = null;
  let circular_std: number | null = null;
  if (stats.variableType?.toLowerCase() === 'circular' && count > 0) {
    let sinSum = 0;
    let cosSum = 0;
    for (const v of sortedValues) {
      const r = (v * Math.PI) / 180;
      sinSum += Math.sin(r);
      cosSum += Math.cos(r);
    }
    const R = Math.sqrt(sinSum * sinSum + cosSum * cosSum) / count;
    rbar = R;
    circular_mean = ((Math.atan2(sinSum, cosSum) * 180) / Math.PI + 360) % 360;
    const cstdRad = Math.sqrt(-2 * Math.log(Math.max(R, 1e-10)));
    circular_std = isFinite(cstdRad) ? (cstdRad * 180) / Math.PI : null;
  }

  const stddev = variance !== null ? Math.sqrt(variance) : null;
  const q01 = quantileFromSortedValues(sortedValues, 0.01);
  const q10 = quantileFromSortedValues(sortedValues, 0.1);
  const q25 = quantileFromSortedValues(sortedValues, 0.25);
  const median = quantileFromSortedValues(sortedValues, 0.5);
  const q75 = quantileFromSortedValues(sortedValues, 0.75);
  const q90 = quantileFromSortedValues(sortedValues, 0.9);
  const q99 = quantileFromSortedValues(sortedValues, 0.99);
  const iqr = q25 !== null && q75 !== null ? q75 - q25 : null;
  const range = min !== null && max !== null ? max - min : null;
  const q10_90_range = q10 !== null && q90 !== null ? q90 - q10 : null;

  return {
    ...stats,
    summary: {
      count,
      min,
      mean,
      max,
      median,
      stddev,
      std: stddev,
      variance,
      range,
      q01,
      q10,
      q25,
      q75,
      q90,
      q99,
      iqr,
      q10_90_range,
      circular_mean,
      rbar,
      circular_std,
    },
    histogram,
    densityCurve:
      stats.variableType?.toLowerCase() === 'circular'
        ? buildCircularKde(sortedValues)
        : buildGaussianKde(sortedValues),
    baselineSummary: stats.summary,
  };
};

const buildScopedStats = ({
  stats,
  locationGid,
  observationsByCatalog,
  locationLookup,
  indexRows,
}: {
  stats: SpeciesEnvironmentStats;
  locationGid?: string | null;
  observationsByCatalog: Record<string, UploadedOccurrenceRow>;
  locationLookup: ReturnType<typeof buildLocationLookupMaps>;
  indexRows: UploadedOccurrenceIndexRow[];
}): SpeciesEnvironmentStats => {
  if (!locationGid) {
    return stats;
  }

  const isCategorical =
    stats.variableType?.toLowerCase() === 'categorical' ||
    stats.variableType?.toLowerCase() === 'nominal' ||
    stats.variableType?.toLowerCase() === 'ordinal' ||
    (stats.categoricalDistribution?.length ?? 0) > 0;

  if (isCategorical) {
    return buildScopedCategoricalStats({
      stats,
      locationGid,
      observationsByCatalog,
      locationLookup,
      indexRows,
    });
  }

  return buildScopedNumericStats({
    stats,
    locationGid,
    observationsByCatalog,
    locationLookup,
    indexRows,
  });
};

const pickOccurrenceObservations = (
  catalogIds: (number | string)[],
  observationsByCatalog: Record<string, UploadedOccurrenceRow>,
): SpeciesEnvironmentObservation[] => {
  return catalogIds
    .map((id) => observationsByCatalog[String(id)])
    .filter(Boolean)
    .map((row) => ({
      catalogNumber: row.catalogNumber,
      value: null,
      latitude: row.latitude,
      longitude: row.longitude,
    }));
};

// ---------------------------------------------------------------------------
// Display-time unit conversion helpers (mirrors wherewild/util/units.py)
// ---------------------------------------------------------------------------

const convertSummaryFields = (
  summary: SpeciesEnvironmentStats['summary'],
  conv: LinearConversion,
): SpeciesEnvironmentStats['summary'] => {
  const pos = (v: number | null | undefined) => applyConv(v, conv);
  const scale = (v: number | null | undefined) => applyConv(v, conv, true);
  return {
    ...summary,
    min: pos(summary.min),
    mean: pos(summary.mean),
    max: pos(summary.max),
    median: pos(summary.median),
    std: scale(summary.std),
    stddev: scale(summary.stddev),
    variance: summary.variance != null ? (conv.scale * conv.scale * summary.variance) : summary.variance,
    range: scale(summary.range),
    q01: pos(summary.q01),
    q10: pos(summary.q10),
    q25: pos(summary.q25),
    q75: pos(summary.q75),
    q90: pos(summary.q90),
    q99: pos(summary.q99),
    iqr: scale(summary.iqr),
    q10_90_range: scale(summary.q10_90_range),
    mode: typeof summary.mode === 'number' ? pos(summary.mode) : summary.mode,
    // rbar, circular_mean, circular_std, unique_classes, entropy, count: unitless — no conversion
  };
};

const convertStats = (
  stats: SpeciesEnvironmentStats,
  conv: LinearConversion,
): SpeciesEnvironmentStats => ({
  ...stats,
  units: conv.unit,
  summary: convertSummaryFields(stats.summary, conv),
  baselineSummary: stats.baselineSummary
    ? convertSummaryFields(stats.baselineSummary, conv)
    : stats.baselineSummary,
  histogram: stats.histogram
    ? { bins: stats.histogram.bins.map((b) => applyConv(b, conv) ?? b), counts: stats.histogram.counts }
    : stats.histogram,
  densityCurve: stats.densityCurve
    ? {
        points: stats.densityCurve.points.map((p) => applyConv(p, conv) ?? p),
        density: stats.densityCurve.density, // normalized by chart — no need to scale
      }
    : stats.densityCurve,
});

export const buildUploadLocalSpeciesDataSource = ({
  bundle,
  speciesId = DEFAULT_SPECIES_ID,
}: BuildLocalSpeciesDataSourceOptions): SpeciesDataSource => {
  validateUploadedParquetBundle(bundle);

  const statsByVariable = buildStatsByVariable(bundle, speciesId);
  const supportedVariableIds = new Set(Object.keys(statsByVariable));
  const occurrences = toSpeciesOccurrences(bundle.occurrences);
  const observationsByCatalog = toObservationsByCatalog(bundle.occurrences);
  const indexRowsByVariable = groupIndexRowsByVariable(bundle.occurrenceIndex);
  const locations = bundle.locations ?? [];
  const locationLookup = buildLocationLookupMaps(locations);

  // Derive parent GID from child GID using GADM format ("AA.N.M_V" → "AA.N_V" → "AA").
  // This avoids name-based lookups which fail when a county shares a name with a state
  // (e.g., "Utah County" in Utah state has GADM name "Utah", shadowing the state in byName).
  const deriveParentGid = (gid: string): string | null => {
    const match = gid.match(/^(.+)\.\d+_\d+$/);
    if (!match) return null;
    const parentCore = match[1];
    if (locationLookup.byGid.has(normalizeLocationToken(parentCore + '_1'))) {
      return parentCore + '_1';
    }
    if (locationLookup.byGid.has(normalizeLocationToken(parentCore))) {
      return parentCore;
    }
    return null;
  };

  // Precompute observation count per location GID and aggregate up to ancestors
  // so fetchSpeciesLocations can sort by count.
  const countByGid = new Map<string, number>();
  for (const row of bundle.occurrences) {
    if (!row.locationGid) continue;
    let current: string | null = row.locationGid;
    while (current) {
      const norm = normalizeLocationToken(current);
      countByGid.set(norm, (countByGid.get(norm) ?? 0) + 1);
      current = deriveParentGid(current);
    }
  }

  return createSpeciesDataSource({
    locationParentIdentityMode: 'gid',
    fetchEnvironmentVariables: async (options) => {
      const rawDefs =
        bundle.variableDefinitions && bundle.variableDefinitions.length > 0
          ? bundle.variableDefinitions.filter((definition) =>
              supportedVariableIds.has(definition.id),
            )
          : Array.from(supportedVariableIds).map((variable) => {
              const stats = statsByVariable[variable];
              return {
                id: variable,
                name: stats.variableName,
                units: stats.units ?? null,
                valueType: stats.variableType ?? null,
                category: null,
                renderMin: null,
                renderMax: null,
              };
            });

      if (options?.units !== 'imperial') return rawDefs;

      return rawDefs.map((def) => {
        const conv = getMetricToImperial(def.units);
        if (!conv) return def;
        return {
          ...def,
          units: conv.unit,
          renderMin: applyConv(def.renderMin, conv) ?? def.renderMin,
          renderMax: applyConv(def.renderMax, conv) ?? def.renderMax,
        };
      });
    },

    fetchSpeciesEnvironment: async (_taxonId, variableId, options) => {
      const stats = statsByVariable[variableId];
      if (!stats) {
        throw new Error(
          `Local upload does not include stats for variable: ${variableId}`,
        );
      }

      const scoped = buildScopedStats({
        stats,
        locationGid: options?.location,
        observationsByCatalog,
        locationLookup,
        indexRows: indexRowsByVariable[variableId] ?? [],
      });

      if (options?.units !== 'imperial') return scoped;
      const conv = getMetricToImperial(scoped.units);
      return conv ? convertStats(scoped, conv) : scoped;
    },

    fetchEnvironmentRangeSlice: async (params) => {
      const indexRows = indexRowsByVariable[params.variableId] ?? [];
      // The occurrence index stores metric values; reverse-convert selection bounds
      // when the caller is working in imperial so the overlap check is apples-to-apples.
      let { min, max } = params;
      if (params.units === 'imperial') {
        const rawStats = statsByVariable[params.variableId];
        const conv = getMetricToImperial(rawStats?.units);
        if (conv) {
          min = reverseConv(min, conv) ?? min;
          max = reverseConv(max, conv) ?? max;
        }
      }
      const catalogs = filterCatalogIdsByLocation(
        collectCatalogsForRange(indexRows, min, max),
        observationsByCatalog,
        locationLookup,
        params.location,
      );
      const observations = pickOccurrenceObservations(
        catalogs,
        observationsByCatalog,
      );

      const response: SpeciesEnvironmentSliceResponse = {
        speciesId,
        variable: params.variableId,
        range: {
          min: params.min,
          max: params.max,
        },
        limit: params.limit ?? null,
        count: observations.length,
        observations,
      };

      return response;
    },

    fetchSpeciesEnvironmentCategorySamples: async (
      _taxonId,
      variableId,
      classValue,
      options,
    ) => {
      const indexRows = indexRowsByVariable[variableId] ?? [];
      const catalogs = filterCatalogIdsByLocation(
        collectCatalogsForCategory(indexRows, classValue),
        observationsByCatalog,
        locationLookup,
        options?.location,
      );
      const observations = pickOccurrenceObservations(
        catalogs,
        observationsByCatalog,
      );

      const response: SpeciesEnvironmentCategorySampleResponse = {
        speciesId,
        variable: variableId,
        classValue,
        count: observations.length,
        observations,
      };

      return response;
    },

    fetchObservationEnvironmentValue: async (
      _taxonId,
      catalogNumber,
      variableId,
      options,
    ) => {
      const stats = statsByVariable[variableId];
      const row = observationsByCatalog[String(catalogNumber)];
      if (!row) {
        return {
          variable: variableId,
          value: null,
          valueLabel: null,
          valueDescription: null,
          units: stats?.units ?? null,
        };
      }

      if (
        !matchesObservationLocation(
          row.locationGid,
          locationLookup,
          options?.location,
        )
      ) {
        return {
          variable: variableId,
          value: null,
          valueLabel: null,
          valueDescription: null,
          units: stats?.units ?? null,
        };
      }

      const rawValue = findObservationEnvironmentValue(
        indexRowsByVariable[variableId] ?? [],
        catalogNumber,
      );
      const conv =
        options?.units === 'imperial' ? getMetricToImperial(stats?.units) : null;
      const value =
        conv && typeof rawValue === 'number'
          ? (applyConv(rawValue, conv) ?? rawValue)
          : rawValue;
      const categoryEntry = findCategoricalDistributionEntry(stats, rawValue);

      return {
        variable: variableId,
        value,
        valueLabel: categoryEntry?.className ?? null,
        valueDescription: categoryEntry?.description ?? null,
        units: conv ? conv.unit : (stats?.units ?? null),
      };
    },

    fetchSpeciesOccurrences: async (_taxonId, options) => {
      const selectedLocation = options?.location;
      const filtered = !selectedLocation
        ? occurrences
        : occurrences.filter((occurrence) => {
            const row = observationsByCatalog[String(occurrence.catalogNumber)];
            if (!row?.locationGid) {
              return false;
            }
            const rowLocation = resolveLocationEntry(
              row.locationGid,
              locationLookup,
            );
            if (!rowLocation) {
              return (
                normalizeLocationToken(row.locationGid) ===
                normalizeLocationToken(selectedLocation)
              );
            }
            return matchesParentLocation(
              rowLocation,
              selectedLocation,
              locationLookup,
            );
          });
      return {
        occurrences: filtered,
        minTimestamp: null,
        maxTimestamp: null,
        phenologyCounts: null,
      };
    },

    fetchSpeciesLocations: async (_taxonId, level, parent, limit = 500) => {
      const normalizedLevel = normalizeLocationLevel(level);
      const filtered = locations.filter((location) => {
        if (
          typeof normalizedLevel === 'number' &&
          location.level !== normalizedLevel
        ) {
          return false;
        }

        if (!parent) {
          return true;
        }

        return matchesParentLocation(location, parent, locationLookup);
      });

      filtered.sort((a, b) => {
        const ca = countByGid.get(normalizeLocationToken(a.gid)) ?? 0;
        const cb = countByGid.get(normalizeLocationToken(b.gid)) ?? 0;
        return cb - ca || a.name.localeCompare(b.name);
      });
      return filtered.slice(0, limit);
    },
  });
};
