/* eslint-env node */
/* global __dirname */
/*
This script syncs the WhereWild theme assets inside the front-end repo.
It optionally refreshes token/style snapshots from Figma, generates the raw CSS
theme file, and then emits a TypeScript module exporting resolved tokens for
use in JS/TS.
*/

const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const FRONT_END_ROOT = path.resolve(__dirname, '..');
const TOKENS_SCRIPT_DIR = path.resolve(FRONT_END_ROOT, 'scripts', 'tokens');
const TOKENS_APP_PATH = path.resolve(TOKENS_SCRIPT_DIR, 'app.mjs');
const TOKENS_JSON_PATH = path.resolve(TOKENS_SCRIPT_DIR, 'tokens.json');
const STYLES_JSON_PATH = path.resolve(TOKENS_SCRIPT_DIR, 'styles.json');
const TARGET_CSS_PATH = path.resolve(
  FRONT_END_ROOT,
  'constants',
  'wds-theme.css',
);
const TARGET_TS_PATH = path.resolve(
  FRONT_END_ROOT,
  'constants',
  'wdsTokens.ts',
);
const cliArgs = new Set(process.argv.slice(2));
const forceRestApi = cliArgs.has('--rest-api');
const skipRestApi = cliArgs.has('--skip-rest-api');
const hasFigmaCredentials = Boolean(
  process.env.FIGMA_ACCESS_TOKEN && process.env.FIGMA_FILE_KEY,
);
const shouldFetchFromFigma = forceRestApi;

if (forceRestApi && skipRestApi) {
  console.error('Choose either --rest-api or --skip-rest-api, not both.');
  process.exit(1);
}

if (forceRestApi && !hasFigmaCredentials) {
  console.error(
    'FIGMA_ACCESS_TOKEN and FIGMA_FILE_KEY are required when using --rest-api.',
  );
  process.exit(1);
}

if (!shouldFetchFromFigma) {
  const missingSnapshotPaths = [TOKENS_JSON_PATH, STYLES_JSON_PATH].filter(
    (filePath) => !fs.existsSync(filePath),
  );
  if (missingSnapshotPaths.length > 0) {
    console.error(
      'Unable to run theme sync without local Figma snapshot files. ' +
      'Either export scripts/tokens/tokens.json and scripts/tokens/styles.json ' +
      'with the bundled Figma plugins, or rerun with --rest-api plus ' +
      'FIGMA_ACCESS_TOKEN and FIGMA_FILE_KEY set.',
    );
    process.exit(1);
  }
}

const tokenScriptArgs = [TOKENS_APP_PATH];
if (!shouldFetchFromFigma) {
  tokenScriptArgs.push('--skip-rest-api');
}

const syncResult = spawnSync(process.execPath, tokenScriptArgs, {
  cwd: TOKENS_SCRIPT_DIR,
  env: process.env,
  stdio: 'inherit',
});

if (syncResult.status !== 0) {
  const signalSuffix = syncResult.signal
    ? ` (signal: ${syncResult.signal})`
    : '';
  console.error(
    `Theme sync failed while running ${path.relative(
      FRONT_END_ROOT,
      TOKENS_APP_PATH,
    )}${signalSuffix}.`,
  );
  process.exit(syncResult.status || 1);
}

if (!fs.existsSync(TARGET_CSS_PATH)) {
  console.error(
    `Theme sync expected ${path.relative(
      FRONT_END_ROOT,
      TOKENS_APP_PATH,
    )} to generate ${path.relative(FRONT_END_ROOT, TARGET_CSS_PATH)}, ` +
    'but the file was not created.',
  );
  process.exit(1);
}

const cssContents = fs.readFileSync(TARGET_CSS_PATH, 'utf8');

// Buckets that mirror the sections generated by scripts/tokens/app.mjs.
const contexts = {
  colorPrimitives: {},
  newColorPrimitives: {},
  colorLight: {},
  colorDark: {},
  size: {},
  time: {},
  typographyPrimitives: {},
  typography: {},
  styles: {},
  responsiveDesktop: {},
  responsiveTablet: {},
  responsivePhone: {},
};

// Any unexpected sections land here so we can still consume their tokens.
const additionalContexts = {};

let pendingContext = null;
let activeContext = null;
let contextBraceDepth = 0;

// Walk the CSS file line-by-line to figure out which section each block belongs to.
cssContents.split('\n').forEach((line) => {
  const trimmed = line.trim();
  const lower = trimmed.toLowerCase();

  if (trimmed.startsWith('/*')) {
    pendingContext = determinePendingContext(lower);
    return;
  }

  if (pendingContext && trimmed.endsWith('{')) {
    const targetStore = getContextStore(pendingContext);
    if (!targetStore) {
      pendingContext = null;
      return;
    }
    activeContext = pendingContext;
    contextBraceDepth = 1;
    pendingContext = null;
    return;
  }

  if (!activeContext) {
    return;
  }

  if (trimmed.startsWith('}')) {
    contextBraceDepth -= 1;
    if (contextBraceDepth <= 0) {
      activeContext = null;
    }
    return;
  }

  const targetStore = getContextStore(activeContext);
  if (!targetStore) {
    return;
  }

  // Capture every --token: value pair so we can rehydrate it later.
  const match = trimmed.match(/^--([a-z0-9-]+):\s*([^;]+);/i);
  if (match) {
    targetStore[match[1]] = match[2].trim();
  }

  const openCount = (trimmed.match(/\{/g) || []).length;
  const closeCount = (trimmed.match(/\}/g) || []).length;
  if (openCount || closeCount) {
    contextBraceDepth += openCount - closeCount;
    if (contextBraceDepth <= 0) {
      activeContext = null;
    }
  }
});

// Interpret comment headers (e.g. /* color_primitives */) to decide where tokens go next.
function determinePendingContext(commentLower) {
  const cleanedComment = commentLower
    .replace(/^\/\*+\s*/, '')
    .replace(/\s*\*+\/$/, '')
    .trim();
  if (!cleanedComment) {
    return null;
  }
  const normalized = cleanedComment;
  const lowerComment = normalized.toLowerCase();
  const setContext = (key, type = 'contexts') => ({ type, key });

  if (lowerComment.includes('new_color_primitives')) {
    return setContext('newColorPrimitives');
  }
  if (lowerComment.includes('color_primitives')) {
    return setContext('colorPrimitives');
  }
  if (lowerComment.includes('color: wds_light')) {
    return setContext('colorLight');
  }
  if (lowerComment.includes('color: wds_dark')) {
    return setContext('colorDark');
  }
  if (lowerComment.includes('size:')) {
    return setContext('size');
  }
  if (lowerComment.includes('time:')) {
    return setContext('time');
  }
  if (lowerComment.includes('typography_primitives')) {
    return setContext('typographyPrimitives');
  }
  if (lowerComment.includes('typography:') && !lowerComment.includes('typography_primitives')) {
    return setContext('typography');
  }
  if (lowerComment.includes('styles')) {
    return setContext('styles');
  }
  if (lowerComment.startsWith('responsive:')) {
    const variant = lowerComment
      .split(':')[1]
      .replace(/\([^)]*\)/g, '')
      .trim() || 'desktop';
    const key = `responsive${variant
      .split(/[^a-z0-9]+/i)
      .filter(Boolean)
      .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
      .join('')}`;
    if (!contexts[key]) {
      contexts[key] = {};
    }
    return setContext(key);
  }

  // Unknown sections (like future token groups) end up in "additional" buckets.
  const fallbackKey =
    lowerComment
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .trim() || 'misc';
  if (!additionalContexts[fallbackKey]) {
    additionalContexts[fallbackKey] = {};
    console.warn(
      `Captured additional token section "${normalized}" into bucket "${fallbackKey}". ` +
      'Consider adding explicit handling if these tokens need special processing.',
    );
  }
  return setContext(fallbackKey, 'additional');
}

// Resolve a storage bucket given the descriptor produced by determinePendingContext.
function getContextStore(contextDescriptor) {
  if (!contextDescriptor) return null;
  if (contextDescriptor.type === 'contexts') {
    contexts[contextDescriptor.key] = contexts[contextDescriptor.key] || {};
    return contexts[contextDescriptor.key];
  }
  if (contextDescriptor.type === 'additional') {
    additionalContexts[contextDescriptor.key] =
      additionalContexts[contextDescriptor.key] || {};
    return additionalContexts[contextDescriptor.key];
  }
  return null;
}

// Convert a raw context map into one where every value has been resolved.
// dependencyContext lets semantic layers reuse primitive definitions.
// Resolve CSS variable references (var(--foo)) so consumers can import pure values.
const resolveContext = (rawContext, dependencyContext = {}) => {
  const combinedRaw = { ...dependencyContext, ...rawContext };
  const cache = {};

  const resolveToken = (name, stack = new Set([name])) => {
    if (cache[name]) {
      return cache[name];
    }

    const rawValue = combinedRaw[name];
    if (rawValue === undefined) {
      return undefined;
    }

    const simpleVarMatch = rawValue.match(/^var\((--[a-z0-9-]+)\)$/i);
    if (simpleVarMatch) {
      const referencedName = simpleVarMatch[1].replace(/^--/, '');
      if (stack.has(referencedName)) {
        throw new Error(
          `Circular token reference detected: ${[
            ...stack,
            referencedName,
          ].join(' -> ')}`,
        );
      }
      const nextStack = new Set(stack);
      nextStack.add(referencedName);
      const resolvedReference = resolveToken(referencedName, nextStack);
      cache[name] = resolvedReference ?? rawValue;
      return cache[name];
    }

    cache[name] = rawValue;
    return rawValue;
  };

  const resolved = {};
  Object.keys(rawContext).forEach((tokenName) => {
    resolved[tokenName] = resolveToken(tokenName);
  });
  return resolved;
};

// Combine legacy + "new" color primitives; the app wants a single palette map.
const mergedColorPrimitives = {
  ...contexts.colorPrimitives,
  ...contexts.newColorPrimitives,
};
const resolvedColorPrimitives = resolveContext(mergedColorPrimitives);
// Semantic maps start with primitives but also include their own overrides.
const resolvedLight = resolveContext(contexts.colorLight, {
  ...mergedColorPrimitives,
  ...contexts.colorLight,
});
const resolvedDark = resolveContext(contexts.colorDark, {
  ...mergedColorPrimitives,
  ...contexts.colorDark,
});

const resolvedSizeTokens = resolveContext(contexts.size);
const resolvedTimeTokens = resolveContext(contexts.time, {
  ...mergedColorPrimitives,
  ...contexts.size,
  ...contexts.typographyPrimitives,
  ...contexts.typography,
  ...contexts.styles,
  ...contexts.time,
});
const resolvedTypographyPrimitives = resolveContext(
  contexts.typographyPrimitives,
);
const resolvedTypography = resolveContext(contexts.typography, {
  ...contexts.typographyPrimitives,
  ...contexts.typography,
});
const resolvedStyleTokens = resolveContext(contexts.styles, {
  ...contexts.typographyPrimitives,
  ...contexts.typography,
  ...contexts.styles,
});

// Responsive tokens can reference typography/size/etc, so preload those maps.
const responsiveDependencyContext = {
  ...mergedColorPrimitives,
  ...contexts.size,
  ...contexts.typographyPrimitives,
  ...contexts.typography,
  ...contexts.styles,
};

// Include every responsive variant discovered from comment headers (e.g. desktop/tablet/phone).
const getResponsiveVariantTier = (variant) => {
  const normalized = variant.toLowerCase();
  if (normalized === 'desktop') return 0;
  if (normalized === 'tablet') return 1;
  if (normalized === 'phone') return 2;
  return 3;
};

const responsiveContextEntries = Object.entries(contexts)
  .filter(([key, ctx]) => key.startsWith('responsive') && Object.keys(ctx).length > 0)
  .map(([key, ctx]) => {
    const rawVariant = key.replace(/^responsive/, '');
    const variant = rawVariant
      ? rawVariant.charAt(0).toLowerCase() + rawVariant.slice(1)
      : 'desktop';
    return [variant, ctx];
  })
  .sort(([a], [b]) => {
    const aTier = getResponsiveVariantTier(a);
    const bTier = getResponsiveVariantTier(b);
    if (aTier !== bTier) {
      return aTier - bTier;
    }
    return a.localeCompare(b);
  });

const resolvedResponsiveTokens = Object.fromEntries(
  responsiveContextEntries.map(([variant, ctx]) => [
    variant,
    resolveContext(ctx, responsiveDependencyContext),
  ]),
);

const resolvedAdditionalTokenTables = Object.fromEntries(
  Object.entries(additionalContexts)
    .filter(([, ctx]) => Object.keys(ctx).length > 0)
    .map(([key, ctx]) => [key, resolveContext(ctx, responsiveDependencyContext)]),
);

const DEFAULT_SOURCE_LABEL = shouldFetchFromFigma
  ? 'Figma REST API -> scripts/tokens/{tokens.json,styles.json}'
  : 'scripts/tokens/{tokens.json,styles.json}';
const SOURCE_LABEL = process.env.DESIGN_SYSTEM_SOURCE_LABEL || DEFAULT_SOURCE_LABEL;

// Stamp the generated TS file with context about the source file.
const headerComment =
  '/**\n' +
  ' * Auto-generated by scripts/sync-theme.cjs\n' +
  ` * Source: ${SOURCE_LABEL}\n` +
  ' */\n';

// Build the TypeScript module that mirrors the CSS token data.
const tokensTs =
  `${headerComment}` +
  // Primitive table export
  `export const wdsPrimitiveTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedColorPrimitives).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  // Serialize primitives and both semantic modes into a TS module
  `export const wdsSemanticTokens = {\n` +
  `  light: ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedLight).sort(([a], [b]) => a.localeCompare(b)),
    ),
    null,
    2,
  ).replace(/\n/g, '\n  ')} as const,\n` +
  `  dark: ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedDark).sort(([a], [b]) => a.localeCompare(b)),
    ),
    null,
    2,
  ).replace(/\n/g, '\n  ')} as const,\n` +
  `} as const;\n\n` +
  `export const wdsSizeTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedSizeTokens).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  `export const wdsTimeTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedTimeTokens).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  `export const wdsTypographyPrimitiveTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedTypographyPrimitives).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  `export const wdsTypographyTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedTypography).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  `export const wdsStyleTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedStyleTokens).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  (responsiveContextEntries.length
    ? `export const wdsResponsiveTokens = ${JSON.stringify(
      Object.fromEntries(
        Object.entries(resolvedResponsiveTokens).sort(([a], [b]) =>
          a.localeCompare(b),
        ),
      ),
      null,
      2,
    )} as const;\n\n`
    : '') +
  (Object.keys(resolvedAdditionalTokenTables).length
    ? `export const wdsAdditionalTokenTables = ${JSON.stringify(
      Object.fromEntries(
        Object.entries(resolvedAdditionalTokenTables).sort(([a], [b]) =>
          a.localeCompare(b),
        ),
      ),
      null,
      2,
    )} as const;\n\n`
    : '') +
  // Helpful types for consumers
  `export type WdsPrimitiveTokenName = keyof typeof wdsPrimitiveTokens;\n` +
  `export type WdsSemanticMode = keyof typeof wdsSemanticTokens;\n` +
  `export type WdsSemanticTokenName = keyof (typeof wdsSemanticTokens)[WdsSemanticMode];\n` +
  `export type WdsSizeTokenName = keyof typeof wdsSizeTokens;\n` +
  `export type WdsTimeTokenName = keyof typeof wdsTimeTokens;\n` +
  `export type WdsTypographyPrimitiveTokenName = keyof typeof wdsTypographyPrimitiveTokens;\n` +
  `export type WdsTypographyTokenName = keyof typeof wdsTypographyTokens;\n` +
  `export type WdsStyleTokenName = keyof typeof wdsStyleTokens;\n` +
  (responsiveContextEntries.length
    ? `export type WdsResponsiveVariant = keyof typeof wdsResponsiveTokens;\n` +
    `export type WdsResponsiveTokenName = keyof (typeof wdsResponsiveTokens)[WdsResponsiveVariant];\n`
    : '') +
  (Object.keys(resolvedAdditionalTokenTables).length
    ? `export type WdsAdditionalTokenBucket = keyof typeof wdsAdditionalTokenTables;\n` +
    `export type WdsAdditionalTokenName = keyof (typeof wdsAdditionalTokenTables)[WdsAdditionalTokenBucket];\n`
    : '');

fs.writeFileSync(TARGET_TS_PATH, tokensTs, 'utf8');

// Emit a quick summary so devs know what changed without opening the file.
const summaryParts = [
  `color primitives: ${Object.keys(resolvedColorPrimitives).length}`,
  `color semantics: ${Object.keys(resolvedLight).length} light / ${Object.keys(
    resolvedDark,
  ).length} dark`,
  `sizes: ${Object.keys(resolvedSizeTokens).length}`,
  `time: ${Object.keys(resolvedTimeTokens).length}`,
  `typography primitives: ${Object.keys(resolvedTypographyPrimitives).length
  }`,
  `typography: ${Object.keys(resolvedTypography).length}`,
  `styles: ${Object.keys(resolvedStyleTokens).length}`,
];

if (responsiveContextEntries.length) {
  summaryParts.push(
    `responsive variants: ${responsiveContextEntries
      .map(([variant]) => `${variant} (${Object.keys(resolvedResponsiveTokens[variant] || {}).length})`)
      .join(', ')}`,
  );
}

const additionalKeys = Object.keys(resolvedAdditionalTokenTables);
if (additionalKeys.length) {
  summaryParts.push(`additional token buckets: ${additionalKeys.join(', ')}`);
}

console.log(
  `Synced ${path.relative(
    FRONT_END_ROOT,
    TARGET_CSS_PATH,
  )} and generated ${path.relative(FRONT_END_ROOT, TARGET_TS_PATH)} ` +
  `(${summaryParts.join(', ')}).`,
);
