/* eslint-env node */
/* global __dirname */
/*
This script syncs the CSS theme definitions from the wherewild-design-system
repository into the front-end codebase. It copies the raw CSS file and also
generates a TypeScript module exporting resolved theme tokens for use in JS/TS.

To run this script, ensure that the wherewild-design-system repo is checked out
and set DESIGN_SYSTEM_PATH to its root, then execute:

  DESIGN_SYSTEM_PATH=../wherewild-design-system npm run sync-theme

This script was written by OpenAI's GPT-5.1-Codex.
*/

const fs = require('node:fs');
const path = require('node:path');

// Resolve key paths relative to this script so the dev doesn't need to pass args.
const FRONT_END_ROOT = path.resolve(__dirname, '..');
const DEFAULT_DESIGN_SYSTEM_ROOT = path.resolve(FRONT_END_ROOT, '../wherewild-design-system');
const DESIGN_SYSTEM_ROOT = process.env.DESIGN_SYSTEM_PATH
  ? path.resolve(process.env.DESIGN_SYSTEM_PATH)
  : DEFAULT_DESIGN_SYSTEM_ROOT;
const DESIGN_SYSTEM_THEME = path.resolve(DESIGN_SYSTEM_ROOT, 'src/theme.css');
const TARGET_CSS_PATH = path.resolve(
  FRONT_END_ROOT,
  'constants',
  'wds-theme.css',
);
const TARGET_TS_PATH = path.resolve(
  FRONT_END_ROOT,
  'constants',
  'wdsTokens.ts',
);

// Fail loudly if the design-system repo hasn't been checked out yet.
if (!fs.existsSync(DESIGN_SYSTEM_THEME)) {
  console.error(
    `Unable to find theme.css at ${DESIGN_SYSTEM_THEME}. ` +
      'Set DESIGN_SYSTEM_PATH to the wherewild-design-system repo root if it is not checked out next to the front end.',
  );
  process.exit(1);
}

// Copy raw CSS so Expo web has direct access to the exact token values.
const cssContents = fs.readFileSync(DESIGN_SYSTEM_THEME, 'utf8');
fs.mkdirSync(path.dirname(TARGET_CSS_PATH), { recursive: true });
fs.writeFileSync(TARGET_CSS_PATH, cssContents, 'utf8');

// Buckets that mirror the sections generated by scripts/tokens/app.mjs.
const contexts = {
  colorPrimitives: {},
  newColorPrimitives: {},
  colorLight: {},
  colorDark: {},
  size: {},
  typographyPrimitives: {},
  typography: {},
  styles: {},
  responsiveDesktop: {},
  responsiveMobile: {},
  responsiveTablet: {},
};

// Any unexpected sections land here so we can still consume their tokens.
const additionalContexts = {};

let pendingContext = null;
let activeContext = null;
let contextBraceDepth = 0;

// Walk the CSS file line-by-line to figure out which section each block belongs to.
cssContents.split('\n').forEach((line) => {
  const trimmed = line.trim();
  const lower = trimmed.toLowerCase();

  if (trimmed.startsWith('/*')) {
    pendingContext = determinePendingContext(lower);
    return;
  }

  if (pendingContext && trimmed.endsWith('{')) {
    const targetStore = getContextStore(pendingContext);
    if (!targetStore) {
      pendingContext = null;
      return;
    }
    activeContext = pendingContext;
    contextBraceDepth = 1;
    pendingContext = null;
    return;
  }

  if (!activeContext) {
    return;
  }

  if (trimmed.startsWith('}')) {
    contextBraceDepth -= 1;
    if (contextBraceDepth <= 0) {
      activeContext = null;
    }
    return;
  }

  const targetStore = getContextStore(activeContext);
  if (!targetStore) {
    return;
  }

  // Capture every --token: value pair so we can rehydrate it later.
  const match = trimmed.match(/^--([a-z0-9-]+):\s*([^;]+);/i);
  if (match) {
    targetStore[match[1]] = match[2].trim();
  }

  const openCount = (trimmed.match(/\{/g) || []).length;
  const closeCount = (trimmed.match(/\}/g) || []).length;
  if (openCount || closeCount) {
    contextBraceDepth += openCount - closeCount;
    if (contextBraceDepth <= 0) {
      activeContext = null;
    }
  }
});

// Interpret comment headers (e.g. /* color_primitives */) to decide where tokens go next.
function determinePendingContext(commentLower) {
  const cleanedComment = commentLower
    .replace(/^\/\*+\s*/, '')
    .replace(/\s*\*+\/$/, '')
    .trim();
  if (!cleanedComment) {
    return null;
  }
  const normalized = cleanedComment;
  const lowerComment = normalized.toLowerCase();
  const setContext = (key, type = 'contexts') => ({ type, key });

  if (lowerComment.includes('new_color_primitives')) {
    return setContext('newColorPrimitives');
  }
  if (lowerComment.includes('color_primitives')) {
    return setContext('colorPrimitives');
  }
  if (lowerComment.includes('color: wds_light')) {
    return setContext('colorLight');
  }
  if (lowerComment.includes('color: wds_dark')) {
    return setContext('colorDark');
  }
  if (lowerComment.includes('size:')) {
    return setContext('size');
  }
  if (lowerComment.includes('typography_primitives')) {
    return setContext('typographyPrimitives');
  }
  if (lowerComment.includes('typography:') && !lowerComment.includes('typography_primitives')) {
    return setContext('typography');
  }
  if (lowerComment.includes('styles')) {
    return setContext('styles');
  }
  if (lowerComment.startsWith('responsive:')) {
    const variant = lowerComment
      .split(':')[1]
      .replace(/\([^)]*\)/g, '')
      .trim() || 'desktop';
    const key = `responsive${variant
      .split(/[^a-z0-9]+/i)
      .filter(Boolean)
      .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
      .join('')}`;
    if (!contexts[key]) {
      contexts[key] = {};
    }
    return setContext(key);
  }

  // Unknown sections (like future token groups) end up in "additional" buckets.
  const fallbackKey =
    lowerComment
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .trim() || 'misc';
  if (!additionalContexts[fallbackKey]) {
    additionalContexts[fallbackKey] = {};
    console.warn(
      `Captured additional token section "${normalized}" into bucket "${fallbackKey}". ` +
        'Consider adding explicit handling if these tokens need special processing.',
    );
  }
  return setContext(fallbackKey, 'additional');
}

// Resolve a storage bucket given the descriptor produced by determinePendingContext.
function getContextStore(contextDescriptor) {
  if (!contextDescriptor) return null;
  if (contextDescriptor.type === 'contexts') {
    contexts[contextDescriptor.key] = contexts[contextDescriptor.key] || {};
    return contexts[contextDescriptor.key];
  }
  if (contextDescriptor.type === 'additional') {
    additionalContexts[contextDescriptor.key] =
      additionalContexts[contextDescriptor.key] || {};
    return additionalContexts[contextDescriptor.key];
  }
  return null;
}

// Convert a raw context map into one where every value has been resolved.
// dependencyContext lets semantic layers reuse primitive definitions.
// Resolve CSS variable references (var(--foo)) so consumers can import pure values.
const resolveContext = (rawContext, dependencyContext = {}) => {
  const combinedRaw = { ...dependencyContext, ...rawContext };
  const cache = {};

  const resolveToken = (name, stack = new Set([name])) => {
    if (cache[name]) {
      return cache[name];
    }

    const rawValue = combinedRaw[name];
    if (rawValue === undefined) {
      return undefined;
    }

    const simpleVarMatch = rawValue.match(/^var\((--[a-z0-9-]+)\)$/i);
    if (simpleVarMatch) {
      const referencedName = simpleVarMatch[1].replace(/^--/, '');
      if (stack.has(referencedName)) {
        throw new Error(
          `Circular token reference detected: ${[
            ...stack,
            referencedName,
          ].join(' -> ')}`,
        );
      }
      const nextStack = new Set(stack);
      nextStack.add(referencedName);
      const resolvedReference = resolveToken(referencedName, nextStack);
      cache[name] = resolvedReference ?? rawValue;
      return cache[name];
    }

    cache[name] = rawValue;
    return rawValue;
  };

  const resolved = {};
  Object.keys(rawContext).forEach((tokenName) => {
    resolved[tokenName] = resolveToken(tokenName);
  });
  return resolved;
};

// Combine legacy + "new" color primitives; the app wants a single palette map.
const mergedColorPrimitives = {
  ...contexts.colorPrimitives,
  ...contexts.newColorPrimitives,
};
const resolvedColorPrimitives = resolveContext(mergedColorPrimitives);
// Semantic maps start with primitives but also include their own overrides.
const resolvedLight = resolveContext(contexts.colorLight, {
  ...mergedColorPrimitives,
  ...contexts.colorLight,
});
const resolvedDark = resolveContext(contexts.colorDark, {
  ...mergedColorPrimitives,
  ...contexts.colorDark,
});

const resolvedSizeTokens = resolveContext(contexts.size);
const resolvedTypographyPrimitives = resolveContext(
  contexts.typographyPrimitives,
);
const resolvedTypography = resolveContext(contexts.typography, {
  ...contexts.typographyPrimitives,
  ...contexts.typography,
});
const resolvedStyleTokens = resolveContext(contexts.styles, {
  ...contexts.typographyPrimitives,
  ...contexts.typography,
  ...contexts.styles,
});

// Responsive tokens can reference typography/size/etc, so preload those maps.
const responsiveDependencyContext = {
  ...mergedColorPrimitives,
  ...contexts.size,
  ...contexts.typographyPrimitives,
  ...contexts.typography,
  ...contexts.styles,
};

// Only include responsive variants that actually contain tokens.
const responsiveContextEntries = [
  ['desktop', contexts.responsiveDesktop],
  ['mobile', contexts.responsiveMobile],
  ['tablet', contexts.responsiveTablet],
].filter(([, ctx]) => Object.keys(ctx).length > 0);

const resolvedResponsiveTokens = Object.fromEntries(
  responsiveContextEntries.map(([variant, ctx]) => [
    variant,
    resolveContext(ctx, responsiveDependencyContext),
  ]),
);

const resolvedAdditionalTokenTables = Object.fromEntries(
  Object.entries(additionalContexts)
    .filter(([, ctx]) => Object.keys(ctx).length > 0)
    .map(([key, ctx]) => [key, resolveContext(ctx, responsiveDependencyContext)]),
);

const DEFAULT_SOURCE_LABEL = 'wherewild-design-system/src/theme.css';
const SOURCE_LABEL = process.env.DESIGN_SYSTEM_SOURCE_LABEL || DEFAULT_SOURCE_LABEL;

// Stamp the generated TS file with context about the source file.
const headerComment =
  '/**\n' +
  ' * Auto-generated by scripts/sync-theme.cjs\n' +
  ` * Source: ${SOURCE_LABEL}\n` +
  ' */\n';

// Build the TypeScript module that mirrors the CSS token data.
const tokensTs =
  `${headerComment}` +
  // Primitive table export
  `export const wdsPrimitiveTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedColorPrimitives).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  // Serialize primitives and both semantic modes into a TS module
  `export const wdsSemanticTokens = {\n` +
  `  light: ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedLight).sort(([a], [b]) => a.localeCompare(b)),
    ),
    null,
    2,
  ).replace(/\n/g, '\n  ')} as const,\n` +
  `  dark: ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedDark).sort(([a], [b]) => a.localeCompare(b)),
    ),
    null,
    2,
  ).replace(/\n/g, '\n  ')} as const,\n` +
  `} as const;\n\n` +
  `export const wdsSizeTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedSizeTokens).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  `export const wdsTypographyPrimitiveTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedTypographyPrimitives).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  `export const wdsTypographyTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedTypography).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  `export const wdsStyleTokens = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(resolvedStyleTokens).sort(([a], [b]) =>
        a.localeCompare(b),
      ),
    ),
    null,
    2,
  )} as const;\n\n` +
  (responsiveContextEntries.length
    ? `export const wdsResponsiveTokens = ${JSON.stringify(
        Object.fromEntries(
          Object.entries(resolvedResponsiveTokens).sort(([a], [b]) =>
            a.localeCompare(b),
          ),
        ),
        null,
        2,
      )} as const;\n\n`
    : '') +
  (Object.keys(resolvedAdditionalTokenTables).length
    ? `export const wdsAdditionalTokenTables = ${JSON.stringify(
        Object.fromEntries(
          Object.entries(resolvedAdditionalTokenTables).sort(([a], [b]) =>
            a.localeCompare(b),
          ),
        ),
        null,
        2,
      )} as const;\n\n`
    : '') +
  // Helpful types for consumers
  `export type WdsPrimitiveTokenName = keyof typeof wdsPrimitiveTokens;\n` +
  `export type WdsSemanticMode = keyof typeof wdsSemanticTokens;\n` +
  `export type WdsSemanticTokenName = keyof (typeof wdsSemanticTokens)[WdsSemanticMode];\n` +
  `export type WdsSizeTokenName = keyof typeof wdsSizeTokens;\n` +
  `export type WdsTypographyPrimitiveTokenName = keyof typeof wdsTypographyPrimitiveTokens;\n` +
  `export type WdsTypographyTokenName = keyof typeof wdsTypographyTokens;\n` +
  `export type WdsStyleTokenName = keyof typeof wdsStyleTokens;\n` +
  (responsiveContextEntries.length
    ? `export type WdsResponsiveVariant = keyof typeof wdsResponsiveTokens;\n` +
      `export type WdsResponsiveTokenName = keyof (typeof wdsResponsiveTokens)[WdsResponsiveVariant];\n`
    : '') +
  (Object.keys(resolvedAdditionalTokenTables).length
    ? `export type WdsAdditionalTokenBucket = keyof typeof wdsAdditionalTokenTables;\n` +
      `export type WdsAdditionalTokenName = keyof (typeof wdsAdditionalTokenTables)[WdsAdditionalTokenBucket];\n`
    : '');

fs.writeFileSync(TARGET_TS_PATH, tokensTs, 'utf8');

// Emit a quick summary so devs know what changed without opening the file.
const summaryParts = [
  `color primitives: ${Object.keys(resolvedColorPrimitives).length}`,
  `color semantics: ${Object.keys(resolvedLight).length} light / ${Object.keys(
    resolvedDark,
  ).length} dark`,
  `sizes: ${Object.keys(resolvedSizeTokens).length}`,
  `typography primitives: ${
    Object.keys(resolvedTypographyPrimitives).length
  }`,
  `typography: ${Object.keys(resolvedTypography).length}`,
  `styles: ${Object.keys(resolvedStyleTokens).length}`,
];

if (responsiveContextEntries.length) {
  summaryParts.push(
    `responsive variants: ${responsiveContextEntries
      .map(([variant]) => `${variant} (${Object.keys(resolvedResponsiveTokens[variant] || {}).length})`)
      .join(', ')}`,
  );
}

const additionalKeys = Object.keys(resolvedAdditionalTokenTables);
if (additionalKeys.length) {
  summaryParts.push(`additional token buckets: ${additionalKeys.join(', ')}`);
}

console.log(
  `Synced ${path.relative(
    FRONT_END_ROOT,
    DESIGN_SYSTEM_THEME,
  )} -> ${path.relative(
    FRONT_END_ROOT,
    TARGET_CSS_PATH,
  )} and generated ${path.relative(
    FRONT_END_ROOT,
    TARGET_TS_PATH,
  )} (${summaryParts.join(', ')}).`,
);
