// AUTO-GENERATED by scripts/gen_colors.py — do not edit by hand.
// Re-run the script to regenerate after updating legend JSON files.

export type CbMode = 'colorblind' | 'achromatopsia';
export type ShapeKey =
  | 'circle' | 'square' | 'triangle' | 'diamond' | 'ring'
  | 'triangle-down' | 'cross' | 'plus' | 'star' | 'hexagon' | 'pentagon' | 'arrow';

/** Maps variable layer_id → CB mode → class ID → CB-safe hex color. */
export const CB_CLASS_COLORS: Record<string, Partial<Record<CbMode, Record<number, string>>>> = {
  kg2: {
    colorblind: { 1: '#2d1d83', 2: '#39278d', 3: '#82c6e8', 4: '#8ed2f4', 5: '#d26b7c', 6: '#c66172', 7: '#e3d27c', 8: '#d7c672', 9: '#2f8c46', 10: '#187b37', 11: '#006b28', 12: '#a4a43e', 13: '#999933', 14: '#8e8f28', 15: '#24843e', 16: '#08732f', 17: '#006320', 18: '#e8e8e8', 19: '#d7d7d7', 20: '#993363', 21: '#770e47', 22: '#bb54a9', 23: '#a43f94', 24: '#993489', 25: '#b0499e', 26: '#e3e3e3', 27: '#cccccc', 28: '#8e285a', 29: '#821c50', 30: '#4aaf9e', 31: '#3ea594' },
    achromatopsia: { 1: '#1b1b1b', 2: '#242424', 3: '#2d2d2d', 4: '#363636', 5: '#494949', 6: '#404040', 7: '#5d5d5d', 8: '#535353', 9: '#757575', 10: '#6e6e6e', 11: '#676767', 12: '#898989', 13: '#828282', 14: '#7a7a7a', 15: '#727272', 16: '#6b6b6b', 17: '#646464', 18: '#a0a0a0', 19: '#959595', 20: '#b7b7b7', 21: '#a6a6a6', 22: '#cecece', 23: '#c2c2c2', 24: '#bcbcbc', 25: '#c8c8c8', 26: '#9a9a9a', 27: '#8f8f8f', 28: '#b1b1b1', 29: '#ababab', 30: '#e2e2e2', 31: '#d7d7d7' },
  },
  landcover: {
    colorblind: { 10: '#e3d27c', 11: '#efdd87', 12: '#d7c672', 20: '#ccbb67', 51: '#157935', 52: '#01702d', 61: '#2f8c46', 62: '#23833d', 71: '#006725', 72: '#006320', 81: '#0c7531', 82: '#006c29', 91: '#298742', 92: '#1d7e39', 120: '#cc6677', 121: '#c05c6d', 122: '#d87081', 130: '#999933', 140: '#a43f94', 150: '#b0499e', 152: '#993489', 153: '#bb54a9', 181: '#3ca392', 182: '#5cc0ae', 183: '#4cb1a0', 184: '#339c8b', 185: '#44aa99', 186: '#54b9a7', 187: '#2a9484', 190: '#882255', 200: '#dddddd', 201: '#d2d2d2', 202: '#e8e8e8', 210: '#332288', 220: '#88ccee' },
    achromatopsia: { 10: '#222222', 11: '#262626', 12: '#1d1d1d', 20: '#191919', 51: '#323232', 52: '#2f2f2f', 61: '#3a3a3a', 62: '#363636', 71: '#2b2b2b', 72: '#292929', 81: '#303030', 82: '#2d2d2d', 91: '#383838', 92: '#343434', 120: '#444444', 121: '#3e3e3e', 122: '#4b4b4b', 130: '#585858', 140: '#6a6a6a', 150: '#6f6f6f', 152: '#656565', 153: '#747474', 181: '#7f7f7f', 182: '#8b8b8b', 183: '#858585', 184: '#7b7b7b', 185: '#828282', 186: '#888888', 187: '#787878', 190: '#989898', 200: '#aeaeae', 201: '#a6a6a6', 202: '#b6b6b6', 210: '#c5c5c5', 220: '#dddddd' },
  },
  landform: {
    colorblind: { 1: '#e4d935', 2: '#00996e', 3: '#006dad', 4: '#f0e442', 5: '#f9ec4b', 6: '#1477b7', 7: '#12a378' },
    achromatopsia: { 1: '#181818', 2: '#727272', 3: '#d7d7d7', 4: '#1f1f1f', 5: '#282828', 6: '#e2e2e2', 7: '#7c7c7c' },
  },
  lithology: {
    colorblind: { 1: '#cc79a7', 2: '#e86e18', 3: '#c16f9c', 4: '#c24e00', 5: '#e09a00', 6: '#f9af21', 7: '#0072b2', 8: '#d784b2', 9: '#db6309', 10: '#009e73', 11: '#d38f00', 12: '#cf5900', 13: '#eca40e', 14: '#f0e442', 15: '#aaaaaa' },
    achromatopsia: { 1: '#1f1f1f', 2: '#454545', 3: '#181818', 4: '#303030', 5: '#545454', 6: '#636363', 7: '#777777', 8: '#282828', 9: '#3e3e3e', 10: '#989898', 11: '#4d4d4d', 12: '#373737', 13: '#5c5c5c', 14: '#bababa', 15: '#dddddd' },
  },
  salinity: {
    colorblind: { 0: '#009e73', 1: '#f6ea48', 2: '#eade3c', 3: '#1477b7', 4: '#006dad' },
    achromatopsia: { 0: '#1f1f1f', 1: '#7c7c7c', 2: '#727272', 3: '#e2e2e2', 4: '#d7d7d7' },
  },
  weather_code_simple: {
    colorblind: { 0: '#f0e442', 1: '#e26811', 2: '#d55e00', 3: '#c85400', 51: '#1ea97d', 53: '#009e73', 55: '#009369', 61: '#207cbd', 63: '#0072b2', 65: '#0068a7', 71: '#d784b2', 73: '#cc79a7', 75: '#c16f9c' },
    achromatopsia: { 0: '#1f1f1f', 1: '#525252', 2: '#494949', 3: '#404040', 51: '#818181', 53: '#777777', 55: '#6d6d6d', 61: '#b3b3b3', 63: '#a8a8a8', 65: '#9e9e9e', 71: '#e8e8e8', 73: '#dddddd', 75: '#d1d1d1' },
  },
  wrb: {
    colorblind: { 0: '#ee8866', 1: '#37b08f', 2: '#51c6a4', 3: '#661100', 4: '#eedd88', 5: '#ffb5c6', 6: '#bbcc33', 7: '#b6b518', 8: '#992288', 9: '#ffaabb', 10: '#e27d5c', 11: '#77aadd', 12: '#6c9fd2', 13: '#ffc0d1', 14: '#006655', 15: '#aaaa00', 16: '#93d7f9', 17: '#ff9d7a', 18: '#44bb99', 19: '#fa9370', 20: '#9e9f00', 21: '#82b5e8', 22: '#d67352', 23: '#129e8d', 24: '#9fe3ff', 25: '#e794a5', 26: '#f39fb0', 27: '#8dc0f4', 28: '#009483', 29: '#6195c7' },
    achromatopsia: { 0: '#1f1f1f', 1: '#292929', 2: '#333333', 3: '#3d3d3d', 4: '#4d4d4d', 5: '#616161', 6: '#6e6e6e', 7: '#868686', 8: '#919191', 9: '#5d5d5d', 10: '#1d1d1d', 11: '#a4a4a4', 12: '#a0a0a0', 13: '#646464', 14: '#b6b6b6', 15: '#808080', 16: '#c5c5c5', 17: '#252525', 18: '#2e2e2e', 19: '#222222', 20: '#7a7a7a', 21: '#a7a7a7', 22: '#1a1a1a', 23: '#e2e2e2', 24: '#cecece', 25: '#575757', 26: '#5a5a5a', 27: '#ababab', 28: '#d8d8d8', 29: '#9c9c9c' },
  },
};

/** Look up a CB-safe color, falling back to the source color if not covered. */
export function getCbColor(
  variableId: string,
  classId: number,
  cbMode: CbMode | null | undefined,
  fallback: string,
): string {
  if (!cbMode) return fallback;
  // Strip temporal suffix (e.g. weather_code_simple_mode_168h → weather_code_simple)
  const baseId = variableId.replace(/_(avg|sum|mode|snapshot)_\d+h$/i, '');
  return CB_CLASS_COLORS[baseId]?.[cbMode]?.[classId] ?? fallback;
}

/** Maps variable layer_id → class ID → shape key used in achromatopsia mode. */
export const CB_CLASS_SHAPES: Record<string, Record<number, ShapeKey>> = {
  kg2: { 1: 'circle', 2: 'circle', 3: 'square', 4: 'square', 5: 'triangle', 6: 'triangle', 7: 'diamond', 8: 'diamond', 9: 'ring', 10: 'ring', 11: 'ring', 12: 'triangle-down', 13: 'triangle-down', 14: 'triangle-down', 15: 'ring', 16: 'ring', 17: 'ring', 18: 'cross', 19: 'cross', 20: 'plus', 21: 'plus', 22: 'star', 23: 'star', 24: 'star', 25: 'star', 26: 'cross', 27: 'cross', 28: 'plus', 29: 'plus', 30: 'hexagon', 31: 'hexagon' },
  landcover: { 10: 'circle', 11: 'circle', 12: 'circle', 20: 'circle', 51: 'square', 52: 'square', 61: 'square', 62: 'square', 71: 'square', 72: 'square', 81: 'square', 82: 'square', 91: 'square', 92: 'square', 120: 'triangle', 121: 'triangle', 122: 'triangle', 130: 'diamond', 140: 'ring', 150: 'ring', 152: 'ring', 153: 'ring', 181: 'triangle-down', 182: 'triangle-down', 183: 'triangle-down', 184: 'triangle-down', 185: 'triangle-down', 186: 'triangle-down', 187: 'triangle-down', 190: 'cross', 200: 'plus', 201: 'plus', 202: 'plus', 210: 'star', 220: 'hexagon' },
  landform: { 1: 'circle', 2: 'square', 3: 'triangle', 4: 'circle', 5: 'circle', 6: 'triangle', 7: 'square' },
  lithology: { 1: 'circle', 2: 'square', 3: 'circle', 4: 'square', 5: 'triangle', 6: 'triangle', 7: 'diamond', 8: 'circle', 9: 'square', 10: 'ring', 11: 'triangle', 12: 'square', 13: 'triangle', 14: 'triangle-down', 15: 'cross' },
  salinity: { 0: 'circle', 1: 'square', 2: 'square', 3: 'triangle', 4: 'triangle' },
  weather_code_simple: { 0: 'circle', 1: 'square', 2: 'square', 3: 'square', 51: 'triangle', 53: 'triangle', 55: 'triangle', 61: 'diamond', 63: 'diamond', 65: 'diamond', 71: 'ring', 73: 'ring', 75: 'ring' },
  wrb: { 0: 'circle', 1: 'square', 2: 'square', 3: 'triangle', 4: 'diamond', 5: 'ring', 6: 'triangle-down', 7: 'cross', 8: 'plus', 9: 'ring', 10: 'circle', 11: 'star', 12: 'star', 13: 'ring', 14: 'hexagon', 15: 'cross', 16: 'pentagon', 17: 'circle', 18: 'square', 19: 'circle', 20: 'cross', 21: 'star', 22: 'circle', 23: 'arrow', 24: 'pentagon', 25: 'ring', 26: 'ring', 27: 'star', 28: 'arrow', 29: 'star' },
};

/** Look up the shape for a class in achromatopsia mode. */
export function getCbShape(variableId: string, classId: number): ShapeKey {
  const baseId = variableId.replace(/_(avg|sum|mode|snapshot)_\d+h$/i, '');
  return CB_CLASS_SHAPES[baseId]?.[classId] ?? 'circle';
}
