// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-variable-guides-index.mjs — do not edit
// by hand. Add or remove a .md file in this directory and re-run
// `npm run sync:variable-guides` (or `npm run typecheck`/`npm run web`,
// which already do) to regenerate this file.

export const VARIABLE_GUIDES: Record<string, string> = {};
