// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import { Colors, Typography } from '@/constants/theme';
import { fireEvent, render, screen } from '@testing-library/react-native';
import React from 'react';
import { Linking, StyleSheet } from 'react-native';
import { useColorScheme } from '@/hooks/useColorScheme';
import { useTypographyStyles } from '@/hooks/useTypographyStyles';
import { ObservationCard } from '../ObservationCard';

jest.mock('@/hooks/useColorScheme', () => ({
  useColorScheme: jest.fn(() => 'dark'),
}));

jest.mock('@/hooks/useTypographyStyles', () => ({
  useTypographyStyles: jest.fn(),
}));

jest.mock('@/components/text/ThemedText', () => {
  const ReactActual = jest.requireActual<typeof import('react')>('react');
  const { Text } =
    jest.requireActual<typeof import('react-native')>('react-native');

  return {
    ThemedText: ({ children, ...props }: { children?: React.ReactNode }) =>
      ReactActual.createElement(Text, props, children),
  };
});

const mockPush = jest.fn();
jest.mock('expo-router', () => ({
  useRouter: () => ({ push: mockPush }),
  // A path that never matches the taxon link, so RoutePressable's "don't
  // navigate if already on this route" check never suppresses a press.
  usePathname: () => '/__not-the-taxon-page__',
}));

const mockUseColorScheme = useColorScheme as jest.MockedFunction<
  typeof useColorScheme
>;
const mockUseTypographyStyles = useTypographyStyles as jest.MockedFunction<
  typeof useTypographyStyles
>;

describe('ObservationCard', () => {
  beforeEach(() => {
    mockUseColorScheme.mockReturnValue('dark');
    mockUseTypographyStyles.mockReturnValue(Typography.dark);
    mockPush.mockClear();
  });

  it('renders placeholder when no image is provided', () => {
    render(<ObservationCard catalogNumber='123456' />);

    expect(screen.getByTestId('observation-card-placeholder')).toBeTruthy();
    expect(screen.queryByTestId('observation-card-image')).toBeNull();
  });

  it('renders the provided image and hides the placeholder', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        imageUrl='https://example.test/photo.jpg'
      />,
    );

    expect(screen.getByTestId('observation-card-image')).toBeTruthy();
    expect(screen.queryByTestId('observation-card-placeholder')).toBeNull();
  });

  it('shows the observation catalog number', () => {
    render(<ObservationCard catalogNumber='987654' />);

    expect(screen.getByText('#987654')).toBeTruthy();
  });

  it('links the catalog number to the iNaturalist observation page', () => {
    const openURLSpy = jest
      .spyOn(Linking, 'openURL')
      .mockResolvedValue(undefined as never);

    render(<ObservationCard catalogNumber='987654' />);

    fireEvent.press(screen.getByText('#987654'));
    expect(openURLSpy).toHaveBeenCalledWith(
      'https://www.inaturalist.org/observations/987654',
    );

    openURLSpy.mockRestore();
  });

  it('does not link the catalog number when it was auto-generated', () => {
    render(<ObservationCard catalogNumber='987654' catalogAutoGenerated />);

    const catalogText = screen.getByText('#987654');
    expect(catalogText.props.onPress).toBeUndefined();
  });

  it('shows the scientific name, truncated to one line', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        scientificName='Quercus alba'
        taxonId='42'
      />,
    );

    const nameText = screen.getByText('Quercus alba');
    expect(nameText.props.numberOfLines).toBe(1);
  });

  it('navigates to the observed taxon page when the scientific name is pressed', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        scientificName='Quercus alba'
        taxonId='42'
      />,
    );

    fireEvent.press(screen.getByText('Quercus alba'));
    expect(mockPush).toHaveBeenCalledWith({
      pathname: '/species/[...identifier]',
      params: { identifier: ['42', 'quercus-alba'] },
    });
  });

  it('renders the scientific name as plain, non-pressable text when taxonId is missing', () => {
    render(
      <ObservationCard catalogNumber='123456' scientificName='Quercus alba' />,
    );

    fireEvent.press(screen.getByText('Quercus alba'));
    expect(mockPush).not.toHaveBeenCalled();
  });

  it('renders no scientific name line when none is provided', () => {
    render(<ObservationCard catalogNumber='123456' />);

    expect(screen.queryByText(/Quercus/)).toBeNull();
  });

  it('colors the catalog link using the light-mode brand token', () => {
    mockUseColorScheme.mockReturnValue('light');
    mockUseTypographyStyles.mockReturnValue(Typography.light);

    render(<ObservationCard catalogNumber='987654' />);

    const catalogStyle = StyleSheet.flatten(
      screen.getByText('#987654').props.style,
    ) as { color?: string };
    expect(catalogStyle.color).toBe(Colors.light.text.brand.default);
  });

  it('colors the catalog link using the dark-mode brand token', () => {
    mockUseColorScheme.mockReturnValue('dark');
    mockUseTypographyStyles.mockReturnValue(Typography.dark);

    render(<ObservationCard catalogNumber='987654' />);

    const catalogStyle = StyleSheet.flatten(
      screen.getByText('#987654').props.style,
    ) as { color?: string };
    expect(catalogStyle.color).toBe(Colors.dark.text.brand.default);
  });

  it('shows "No data" when no variable value is provided', () => {
    render(<ObservationCard catalogNumber='123456' />);

    expect(screen.getByText('No data')).toBeTruthy();
  });

  it('renders the variable label instead of the no-data fallback when provided', () => {
    render(<ObservationCard catalogNumber='123456' varLabel='12.3°C' />);

    expect(screen.getByText('12.3°C')).toBeTruthy();
    expect(screen.queryByText('No data')).toBeNull();
  });

  it('renders a plain color dot when varShape is not provided', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        varLabel='Loam'
        varColor='#abcdef'
      />,
    );

    expect(screen.getByTestId('observation-card-dot')).toBeTruthy();
    expect(screen.queryByTestId('observation-card-shape')).toBeNull();
  });

  it('renders the matching shape marker instead of a dot when varShape is a recognized shape (shapes mode on for a nominal variable)', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        varLabel='Loam'
        varColor='#abcdef'
        varShape='triangle'
      />,
    );

    expect(screen.getByTestId('observation-card-shape')).toBeTruthy();
    expect(screen.queryByTestId('observation-card-dot')).toBeNull();
  });

  it('falls back to a plain dot for an unrecognized shape value instead of crashing', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        varLabel='Loam'
        varColor='#abcdef'
        varShape='not-a-real-shape'
      />,
    );

    expect(screen.getByTestId('observation-card-dot')).toBeTruthy();
    expect(screen.queryByTestId('observation-card-shape')).toBeNull();
  });

  it('shows a "No media" fallback when no attribution or license is provided, matching the credit row\'s two-line height so cards without media still line up with ones that have it', () => {
    render(<ObservationCard catalogNumber='123456' />);

    expect(screen.getByTestId('observation-card-credit')).toBeTruthy();
    expect(screen.getByText('No media')).toBeTruthy();
  });

  it('renders attribution and license on their own separate lines, not joined by a separator', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        attribution='© Jane Doe'
        license='CC BY-NC 4.0'
      />,
    );

    expect(screen.getByText('© Jane Doe')).toBeTruthy();
    expect(screen.getByText('CC BY-NC 4.0')).toBeTruthy();
    expect(screen.queryByText(/·/)).toBeNull();
  });

  it('renders only the attribution when license is missing', () => {
    render(<ObservationCard catalogNumber='123456' attribution='© Jane Doe' />);

    expect(screen.getByText('© Jane Doe')).toBeTruthy();
    expect(screen.queryByText(/·/)).toBeNull();
  });

  it('renders the license as plain text when no license URL is provided', () => {
    render(<ObservationCard catalogNumber='123456' license='Public domain' />);

    const licenseText = screen.getByText('Public domain');
    expect(licenseText.props.onPress).toBeUndefined();
  });

  it('renders the license as a hyperlink and opens it on press when a URL is provided', () => {
    const openURLSpy = jest
      .spyOn(Linking, 'openURL')
      .mockResolvedValue(undefined as never);

    render(
      <ObservationCard
        catalogNumber='123456'
        license='CC BY-NC 4.0'
        licenseUrl='https://creativecommons.org/licenses/by-nc/4.0/'
      />,
    );

    fireEvent.press(screen.getByText('CC BY-NC 4.0'));
    expect(openURLSpy).toHaveBeenCalledWith(
      'https://creativecommons.org/licenses/by-nc/4.0/',
    );

    openURLSpy.mockRestore();
  });

  it('does not render attribution as a hyperlink', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        attribution='© Jane Doe'
        license='CC BY-NC 4.0'
        licenseUrl='https://creativecommons.org/licenses/by-nc/4.0/'
      />,
    );

    const attributionText = screen.getByText('© Jane Doe');
    expect(attributionText.props.onPress).toBeUndefined();
  });

  it('sizes the image smaller in compact mode', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        imageUrl='https://example.test/photo.jpg'
        size='compact'
      />,
    );

    const wrapperStyle = StyleSheet.flatten(
      screen.getByTestId('observation-card-image-wrapper').props.style,
    ) as { width?: number };
    expect(wrapperStyle.width).toBe(96);
  });

  it('fires onPress when tapped and exposes button accessibility semantics', () => {
    const onPress = jest.fn();
    render(
      <ObservationCard
        catalogNumber='123456'
        onPress={onPress}
        testID='observation-card'
      />,
    );

    fireEvent.press(screen.getByTestId('observation-card'));
    expect(onPress).toHaveBeenCalledTimes(1);
  });

  it('does not expose button accessibility semantics without onPress', () => {
    render(
      <ObservationCard catalogNumber='123456' testID='observation-card' />,
    );

    expect(
      screen.getByTestId('observation-card').props.accessibilityRole,
    ).not.toBe('button');
  });
});
