// SPDX-FileCopyrightText: 2025-2026 The WhereWild Contributors (see CONTRIBUTORS)
//
// SPDX-License-Identifier: AGPL-3.0-or-later

import { Colors, Typography } from '@/constants/theme';
import { fireEvent, render, screen } from '@testing-library/react-native';
import React from 'react';
import { Linking, StyleSheet } from 'react-native';
import { useColorScheme } from '@/hooks/useColorScheme';
import { useTypographyStyles } from '@/hooks/useTypographyStyles';
import { ObservationCard } from '../ObservationCard';

jest.mock('@/hooks/useColorScheme', () => ({
  useColorScheme: jest.fn(() => 'dark'),
}));

jest.mock('@/hooks/useTypographyStyles', () => ({
  useTypographyStyles: jest.fn(),
}));

jest.mock('@/components/text/ThemedText', () => {
  const ReactActual = jest.requireActual<typeof import('react')>('react');
  const { Text } =
    jest.requireActual<typeof import('react-native')>('react-native');

  return {
    ThemedText: ({ children, ...props }: { children?: React.ReactNode }) =>
      ReactActual.createElement(Text, props, children),
  };
});

const mockUseColorScheme = useColorScheme as jest.MockedFunction<
  typeof useColorScheme
>;
const mockUseTypographyStyles = useTypographyStyles as jest.MockedFunction<
  typeof useTypographyStyles
>;

describe('ObservationCard', () => {
  beforeEach(() => {
    mockUseColorScheme.mockReturnValue('dark');
    mockUseTypographyStyles.mockReturnValue(Typography.dark);
  });

  it('renders placeholder when no image is provided', () => {
    render(<ObservationCard catalogNumber='123456' />);

    expect(screen.getByTestId('observation-card-placeholder')).toBeTruthy();
    expect(screen.queryByTestId('observation-card-image')).toBeNull();
  });

  it('renders the provided image and hides the placeholder', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        imageUrl='https://example.test/photo.jpg'
      />,
    );

    expect(screen.getByTestId('observation-card-image')).toBeTruthy();
    expect(screen.queryByTestId('observation-card-placeholder')).toBeNull();
  });

  it('shows the observation catalog number', () => {
    render(<ObservationCard catalogNumber='987654' />);

    expect(screen.getByText('#987654')).toBeTruthy();
  });

  it('links the catalog number to the iNaturalist observation page', () => {
    const openURLSpy = jest
      .spyOn(Linking, 'openURL')
      .mockResolvedValue(undefined as never);

    render(<ObservationCard catalogNumber='987654' />);

    fireEvent.press(screen.getByText('#987654'));
    expect(openURLSpy).toHaveBeenCalledWith(
      'https://www.inaturalist.org/observations/987654',
    );

    openURLSpy.mockRestore();
  });

  it('does not link the catalog number when it was auto-generated', () => {
    render(<ObservationCard catalogNumber='987654' catalogAutoGenerated />);

    const catalogText = screen.getByText('#987654');
    expect(catalogText.props.onPress).toBeUndefined();
  });

  it('colors the catalog link using the light-mode brand token', () => {
    mockUseColorScheme.mockReturnValue('light');
    mockUseTypographyStyles.mockReturnValue(Typography.light);

    render(<ObservationCard catalogNumber='987654' />);

    const catalogStyle = StyleSheet.flatten(
      screen.getByText('#987654').props.style,
    ) as { color?: string };
    expect(catalogStyle.color).toBe(Colors.light.text.brand.default);
  });

  it('colors the catalog link using the dark-mode brand token', () => {
    mockUseColorScheme.mockReturnValue('dark');
    mockUseTypographyStyles.mockReturnValue(Typography.dark);

    render(<ObservationCard catalogNumber='987654' />);

    const catalogStyle = StyleSheet.flatten(
      screen.getByText('#987654').props.style,
    ) as { color?: string };
    expect(catalogStyle.color).toBe(Colors.dark.text.brand.default);
  });

  it('shows "No data" when no variable value is provided', () => {
    render(<ObservationCard catalogNumber='123456' />);

    expect(screen.getByText('No data')).toBeTruthy();
  });

  it('renders the variable label instead of the no-data fallback when provided', () => {
    render(<ObservationCard catalogNumber='123456' varLabel='12.3°C' />);

    expect(screen.getByText('12.3°C')).toBeTruthy();
    expect(screen.queryByText('No data')).toBeNull();
  });

  it('shows a "No media" fallback when no attribution or license is provided', () => {
    render(<ObservationCard catalogNumber='123456' />);

    expect(screen.queryByTestId('observation-card-credit')).toBeNull();
    expect(screen.getByText('No media')).toBeTruthy();
  });

  it('renders attribution and license as separate text, joined by a separator', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        attribution='© Jane Doe'
        license='CC BY-NC 4.0'
      />,
    );

    expect(screen.getByText('© Jane Doe')).toBeTruthy();
    expect(screen.getByText('CC BY-NC 4.0')).toBeTruthy();
    expect(screen.getByText(' · ')).toBeTruthy();
  });

  it('renders only the attribution when license is missing', () => {
    render(<ObservationCard catalogNumber='123456' attribution='© Jane Doe' />);

    expect(screen.getByText('© Jane Doe')).toBeTruthy();
    expect(screen.queryByText(' · ')).toBeNull();
  });

  it('renders the license as plain text when no license URL is provided', () => {
    render(<ObservationCard catalogNumber='123456' license='Public domain' />);

    const licenseText = screen.getByText('Public domain');
    expect(licenseText.props.onPress).toBeUndefined();
  });

  it('renders the license as a hyperlink and opens it on press when a URL is provided', () => {
    const openURLSpy = jest
      .spyOn(Linking, 'openURL')
      .mockResolvedValue(undefined as never);

    render(
      <ObservationCard
        catalogNumber='123456'
        license='CC BY-NC 4.0'
        licenseUrl='https://creativecommons.org/licenses/by-nc/4.0/'
      />,
    );

    fireEvent.press(screen.getByText('CC BY-NC 4.0'));
    expect(openURLSpy).toHaveBeenCalledWith(
      'https://creativecommons.org/licenses/by-nc/4.0/',
    );

    openURLSpy.mockRestore();
  });

  it('does not render attribution as a hyperlink', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        attribution='© Jane Doe'
        license='CC BY-NC 4.0'
        licenseUrl='https://creativecommons.org/licenses/by-nc/4.0/'
      />,
    );

    const attributionText = screen.getByText('© Jane Doe');
    expect(attributionText.props.onPress).toBeUndefined();
  });

  it('sizes the image smaller in compact mode', () => {
    render(
      <ObservationCard
        catalogNumber='123456'
        imageUrl='https://example.test/photo.jpg'
        size='compact'
      />,
    );

    const wrapperStyle = StyleSheet.flatten(
      screen.getByTestId('observation-card-image-wrapper').props.style,
    ) as { width?: number };
    expect(wrapperStyle.width).toBe(96);
  });

  it('fires onPress when tapped and exposes button accessibility semantics', () => {
    const onPress = jest.fn();
    render(
      <ObservationCard
        catalogNumber='123456'
        onPress={onPress}
        testID='observation-card'
      />,
    );

    fireEvent.press(screen.getByTestId('observation-card'));
    expect(onPress).toHaveBeenCalledTimes(1);
  });

  it('does not expose button accessibility semantics without onPress', () => {
    render(
      <ObservationCard catalogNumber='123456' testID='observation-card' />,
    );

    expect(
      screen.getByTestId('observation-card').props.accessibilityRole,
    ).not.toBe('button');
  });
});
